import { createServerFn } from "@tanstack/react-start";
import { requireMysqlAuth } from "@/integrations/mysql/auth-middleware";
import { rows, uuid } from "./db-utils.server";
import { queryRows } from "./mysql.server";
import { makeOtp } from "./security.server";
import { sendMail } from "./mailer.server";

async function loggedSend(to:string,subject:string,html:string,kind:string){let status="sent",error:string|null=null;try{await sendMail(to,subject,html)}catch(e:any){status="failed";error=e?.message||"Email failed";throw e}finally{await queryRows<any>(`INSERT INTO email_log(id,to_email,subject,kind,status,error) VALUES(?,?,?,?,?,?)`,[uuid(),to,subject,kind,status,error])}}
export const sendCustomEmail=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{to:string;subject:string;html:string;kind?:string})=>d).handler(async({data,context})=>{if(!context.roles.some((r:string)=>["it","admin","receptionist"].includes(r)))throw new Error("Not allowed");await loggedSend(data.to,data.subject,data.html,data.kind||"custom");return{ok:true}});
export const sendCustomerOtp=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{customerId:string})=>d).handler(async({data})=>{const c=(await rows<any>(`SELECT id,email,full_name FROM customers WHERE id=?`,[data.customerId]))[0];if(!c)throw new Error("Customer not found");const code=makeOtp();await queryRows<any>(`INSERT INTO email_verification_codes(id,email,code,purpose,expires_at) VALUES(?,?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 5 MINUTE))`,[uuid(),c.email,code,`customer:${c.id}`]);await loggedSend(c.email,"Verify your email — NOVAWORKS",`<p>Hello ${c.full_name},</p><p>Your verification code is <b style="font-size:24px">${code}</b>.</p>`,`customer_otp`);return{ok:true}});
export const verifyCustomerOtp=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{customerId:string;code:string})=>d).handler(async({data})=>{const c=(await rows<any>(`SELECT * FROM customers WHERE id=?`,[data.customerId]))[0];if(!c)throw new Error("Customer not found");const v=(await rows<any>(`SELECT id FROM email_verification_codes WHERE email=? AND purpose=? AND code=? AND expires_at>UTC_TIMESTAMP() ORDER BY created_at DESC LIMIT 1`,[c.email,`customer:${c.id}`,data.code]))[0];if(!v)throw new Error("Invalid or expired code");await queryRows<any>(`UPDATE customers SET email_verified_at=UTC_TIMESTAMP() WHERE id=?`,[c.id]);await queryRows<any>(`DELETE FROM email_verification_codes WHERE email=? AND purpose=?`,[c.email,`customer:${c.id}`]);await loggedSend(c.email,"Welcome to NOVAWORKS",`<h2>Welcome, ${c.full_name}</h2><p>Your email has been verified.</p>`,`customer_welcome`);return{ok:true}});
export const subscribeAndSendOtp=createServerFn({method:"POST"}).validator((d:{email:string;full_name?:string})=>d).handler(async({data})=>{const email=data.email.trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error("Invalid email");const fullName=(data.full_name||"").trim()||null;await queryRows<any>(`INSERT INTO subscribers(id,email,full_name,verified,notify,marketing_consent,unsubscribed_at,otp_code,otp_expires_at) VALUES(?,?,?,?,?,?,NULL,NULL,NULL) ON DUPLICATE KEY UPDATE full_name=COALESCE(VALUES(full_name),full_name),verified=1,notify=1,marketing_consent=1,unsubscribed_at=NULL,otp_code=NULL,otp_expires_at=NULL`,[uuid(),email,fullName,1,1,1]);await loggedSend(email,"Welcome to NOVAWORKS property alerts",`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto"><h2>You're subscribed to NOVAWORKS</h2><p>${fullName?`Hello ${fullName},`:`Hello,`}</p><p>Thank you for subscribing. We'll email you when new NOVAWORKS properties and selected opportunities are published.</p><p>You can unsubscribe from future marketing messages at any time.</p><p style="margin-top:28px">Regards,<br><b>NOVAWORKS</b></p></div>`,`subscriber_welcome`);return{ok:true,email}});
export const verifySubscriberOtp=createServerFn({method:"POST"}).validator((d:{email:string;code:string})=>d).handler(async({data})=>{const r=await queryRows<any>(`UPDATE subscribers SET verified=1,otp_code=NULL,otp_expires_at=NULL WHERE email=? AND otp_code=? AND otp_expires_at>UTC_TIMESTAMP()`,[data.email.trim().toLowerCase(),data.code]);return{ok:true}});
export const notifySubscribersOfProperty=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{propertyId:string})=>d).handler(async({data,context})=>{if(!context.roles.some((r:string)=>["it","admin"].includes(r)))throw new Error("Not allowed");const p=(await rows<any>(`SELECT p.title,p.slug,p.price,p.currency,p.property_type,p.listing_type,p.city,p.district,p.country,p.bedrooms,p.bathrooms,p.area_sqm,(SELECT url FROM property_images i WHERE i.property_id=p.id ORDER BY i.is_cover DESC,i.position ASC LIMIT 1) cover FROM properties p WHERE p.id=?`,[data.propertyId]))[0];if(!p)return{sent:0};const recipients=await rows<any>(`SELECT DISTINCT LOWER(email) email FROM (SELECT email FROM subscribers WHERE verified=1 AND notify=1 AND marketing_consent=1 AND unsubscribed_at IS NULL UNION ALL SELECT email FROM customers WHERE email IS NOT NULL AND email<>'' UNION ALL SELECT email FROM users WHERE email IS NOT NULL AND email<>'' AND active=1 AND email_notifications_enabled=1 UNION ALL SELECT business_email email FROM users WHERE business_email IS NOT NULL AND business_email<>'' AND active=1 AND email_notifications_enabled=1 UNION ALL SELECT secondary_email email FROM users WHERE secondary_email IS NOT NULL AND secondary_email<>'' AND active=1 AND email_notifications_enabled=1) x WHERE email IS NOT NULL AND email<>''`);let sent=0;for(const r of recipients){try{await loggedSend(r.email,`New property: ${p.title}`,`<p style="margin:0 0 18px;color:#5e5a52">A new NOVAWORKS property has just been published.</p>${p.cover?`<img src="${p.cover}" alt="${p.title}" style="display:block;width:100%;max-height:320px;object-fit:cover;border-radius:12px;margin:0 0 20px"/>`:""}<table style="width:100%;border-collapse:collapse;margin:0 0 22px"><tr><td style="padding:8px 0;color:#777">Price</td><td style="padding:8px 0;text-align:right;font-weight:700">${p.currency} ${Number(p.price).toLocaleString()}</td></tr><tr><td style="padding:8px 0;color:#777">Type</td><td style="padding:8px 0;text-align:right">${String(p.property_type||"").replace(/-/g," ")}</td></tr><tr><td style="padding:8px 0;color:#777">Listing</td><td style="padding:8px 0;text-align:right">${p.listing_type||""}</td></tr><tr><td style="padding:8px 0;color:#777">Location</td><td style="padding:8px 0;text-align:right">${[p.district,p.city,p.country].filter(Boolean).join(", ")}</td></tr>${p.bedrooms?`<tr><td style="padding:8px 0;color:#777">Bedrooms</td><td style="padding:8px 0;text-align:right">${p.bedrooms}</td></tr>`:""}${p.area_sqm?`<tr><td style="padding:8px 0;color:#777">Area</td><td style="padding:8px 0;text-align:right">${Number(p.area_sqm).toLocaleString()} sqm</td></tr>`:""}</table><p style="margin:0"><a href="${process.env.APP_URL||process.env.SITE_URL||"https://novaworks.rw"}/properties/${p.slug}" style="display:inline-block;background:#0d0d0d;color:#fff;text-decoration:none;padding:12px 20px;border-radius:8px">View property</a></p>`,`property_alert`);sent++}catch{}}return{sent}});
