import { createServerFn } from "@tanstack/react-start";
import { requireMysqlAuth } from "@/integrations/mysql/auth-middleware";
import { rows,uuid,audit } from "./db-utils.server";
import { queryRows } from "./mysql.server";
import { makeTemporaryPassword,hashPassword } from "./security.server";
import { sendMail } from "./mailer.server";
export const requestPasswordReset=createServerFn({method:"POST"}).validator((d:{email:string;reason?:string})=>d).handler(async({data})=>{const email=data.email.trim().toLowerCase();const u=(await rows<any>(`SELECT id,email,full_name FROM users WHERE LOWER(email)=? OR LOWER(business_email)=? OR LOWER(secondary_email)=? LIMIT 1`,[email,email,email]))[0];if(!u)return{ok:true};const reason=(data.reason||"").trim();if(reason.length<5)throw new Error("Please enter a short reason for the password reset");const open=(await rows<any>(`SELECT id FROM password_reset_requests WHERE user_id=? AND status='pending' LIMIT 1`,[u.id]))[0];if(!open)await queryRows<any>(`INSERT INTO password_reset_requests(id,user_id,email,reason,status) VALUES(?,?,?,?, 'pending')`,[uuid(),u.id,u.email,reason]);return{ok:true}});
// compatibility: reset requests no longer require an OTP before IT review.
export const verifyPasswordResetOtp=createServerFn({method:"POST"}).validator((d:any)=>d).handler(async()=>({ok:true}));
export const listPasswordResetRequests=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{if(!context.roles.includes("it"))throw new Error("Only IT can manage password resets");return rows<any>(`SELECT pr.*,u.full_name,u.business_email,u.secondary_email FROM password_reset_requests pr JOIN users u ON u.id=pr.user_id ORDER BY FIELD(pr.status,'pending','approved','denied'),pr.created_at DESC LIMIT 300`)});
export const approvePasswordReset=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string})=>d).handler(async({data,context})=>{if(!context.roles.includes("it"))throw new Error("Only IT can approve password resets");const r=(await rows<any>(`SELECT pr.*,u.full_name FROM password_reset_requests pr JOIN users u ON u.id=pr.user_id WHERE pr.id=? AND pr.status='pending'`,[data.id]))[0];if(!r)throw new Error("Pending request not found");const pwd=makeTemporaryPassword();await queryRows<any>(`UPDATE users SET password_hash=?,must_change_password=1 WHERE id=?`,[hashPassword(pwd),r.user_id]);await queryRows<any>(`UPDATE password_reset_requests SET status='approved',approved_by=?,resolved_at=UTC_TIMESTAMP() WHERE id=?`,[context.userId,data.id]);await sendMail(r.email,"NOVAWORKS password reset approved",`<p>Hello ${r.full_name},</p><p>IT approved your password reset request.</p><p>Your temporary password is <b>${pwd}</b></p><p>Sign in and change it immediately. It must contain at least 9 characters, uppercase, lowercase, number and symbol.</p>`);await audit(context.userId,"PASSWORD_RESET_APPROVED","user",r.user_id,null,{request_id:data.id});return{ok:true}});
export const denyPasswordReset=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string})=>d).handler(async({data,context})=>{if(!context.roles.includes("it"))throw new Error("Only IT can deny password resets");await queryRows<any>(`UPDATE password_reset_requests SET status='denied',approved_by=?,resolved_at=UTC_TIMESTAMP() WHERE id=? AND status='pending'`,[context.userId,data.id]);await audit(context.userId,"PASSWORD_RESET_DENIED","password_reset",data.id);return{ok:true}});
