import { createServerFn } from "@tanstack/react-start";
import { requireMysqlAuth } from "@/integrations/mysql/auth-middleware";
import { rows,uuid,assertRoles,audit,parseJson,requireFeature } from "./db-utils.server";
import { queryRows,withTransaction } from "./mysql.server";
import { sendMail } from "./mailer.server";
import { sendSms } from "./sms.server";

type Category="maintenance"|"plumbing"|"electrical"|"cleaning"|"security"|"general"|"other";
type Priority="low"|"medium"|"high"|"urgent"|"emergency";
type Status="pending"|"assigned"|"in_progress"|"awaiting_owner"|"completed"|"cancelled";

async function chooseAdmin(){const a=await rows<any>(`SELECT u.id,u.full_name,u.email,u.phone,COUNT(sr.id) pending_count FROM users u JOIN user_roles ur ON ur.user_id=u.id AND ur.role='admin' LEFT JOIN service_requests sr ON sr.assigned_admin_id=u.id AND sr.status IN('pending','assigned','in_progress','awaiting_owner') WHERE u.active=1 GROUP BY u.id ORDER BY pending_count ASC,COALESCE(MAX(sr.requested_at),'1970-01-01') ASC,u.created_at ASC LIMIT 1`);return a[0]??null}
async function adminList(){return rows<any>(`SELECT DISTINCT u.id,u.full_name,u.email,u.phone FROM users u JOIN user_roles ur ON ur.user_id=u.id WHERE ur.role='admin' AND u.active=1`)}
function nest(r:any){return{...r,created_at:r.requested_at,assigned_to:r.assigned_admin_id,customers:{full_name:r.customer_name,email:r.customer_email,phone:r.customer_phone,apartment_no:r.apartment_code,created_by:r.customer_created_by,properties:{title:r.property_title}},service_items:parseJson(r.items_json,[])}}

export const getMyCustomerRecord=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{const c=(await rows<any>(`SELECT c.id,c.full_name,c.email,c.phone,c.national_id,c.nida_verified_at,c.qr_token,t.id tenancy_id,t.status tenancy_status,t.start_date,t.end_date,t.property_id,t.apartment_id,p.title property_title,a.code apartment_code FROM customers c LEFT JOIN tenancies t ON t.customer_id=c.id AND t.status IN('active','reserved','extension_requested') LEFT JOIN properties p ON p.id=t.property_id LEFT JOIN apartments a ON a.id=t.apartment_id WHERE c.user_id=? OR LOWER(c.email)=LOWER(?) ORDER BY t.created_at DESC LIMIT 1`,[context.userId,context.user.email]))[0];if(!c)return null;const today=new Date().toISOString().slice(0,10);const active=!!c.tenancy_id&&c.start_date<=today&&c.end_date>=today&&["active","extension_requested"].includes(c.tenancy_status);const end=c.end_date?new Date(c.end_date):null;const days=end?Math.max(0,Math.ceil((end.getTime()-Date.now())/86400000)):null;return{...c,apartment_no:c.apartment_code,properties:{title:c.property_title},is_currently_staying:active,days_remaining:days}});

export const listMyServiceRequests=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{const rs=await rows<any>(`SELECT sr.*,c.full_name customer_name,c.email customer_email,c.phone customer_phone,a.code apartment_code,p.title property_title,u.full_name assigned_admin_name,(SELECT JSON_ARRAYAGG(JSON_OBJECT('id',si.id,'description',si.description,'quantity',si.quantity,'unit_price',si.unit_price,'currency',si.currency,'vendor',si.vendor,'receipt_url',si.receipt_url)) FROM service_items si WHERE si.service_request_id=sr.id) items_json FROM service_requests sr JOIN customers c ON c.id=sr.customer_id JOIN properties p ON p.id=sr.property_id LEFT JOIN apartments a ON a.id=sr.apartment_id LEFT JOIN users u ON u.id=sr.assigned_admin_id WHERE c.user_id=? OR LOWER(c.email)=LOWER(?) ORDER BY sr.requested_at DESC`,[context.userId,context.user.email]);return rs.map(nest)});

export const listAllServiceRequests=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{await assertRoles(context.userId,["it","admin","receptionist"]);let where="";const params:any[]=[];if(context.roles.includes("admin")&&!context.roles.includes("it")){/* admins can see all business requests */}else if(context.roles.includes("receptionist")&&!context.roles.some((r:string)=>["admin","it"].includes(r))){where=" WHERE sr.status <> 'cancelled' "}const rs=await rows<any>(`SELECT sr.*,c.full_name customer_name,c.email customer_email,c.phone customer_phone,c.created_by customer_created_by,a.code apartment_code,p.title property_title,u.full_name assigned_admin_name,(SELECT JSON_ARRAYAGG(JSON_OBJECT('id',si.id,'description',si.description,'quantity',si.quantity,'unit_price',si.unit_price,'currency',si.currency,'vendor',si.vendor,'receipt_url',si.receipt_url,'owner_chargeable',si.owner_chargeable)) FROM service_items si WHERE si.service_request_id=sr.id) items_json FROM service_requests sr JOIN customers c ON c.id=sr.customer_id JOIN properties p ON p.id=sr.property_id LEFT JOIN apartments a ON a.id=sr.apartment_id LEFT JOIN users u ON u.id=sr.assigned_admin_id ${where} ORDER BY FIELD(sr.priority,'emergency','urgent','high','medium','low'),sr.requested_at DESC LIMIT 500`,params);return rs.map(nest)});

export const createServiceRequest=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{title:string;description:string;category:Category;priority:Priority;image_urls?:string[];service_catalog_id?:string})=>d).handler(async({data,context})=>{await requireFeature("service_requests");const customer=(await rows<any>(`SELECT c.*,t.id tenancy_id,t.property_id,t.apartment_id,t.start_date,t.end_date,p.title property_title,a.code apartment_code FROM customers c JOIN tenancies t ON t.customer_id=c.id AND t.status IN('active','extension_requested') JOIN properties p ON p.id=t.property_id JOIN apartments a ON a.id=t.apartment_id WHERE c.user_id=? OR LOWER(c.email)=LOWER(?) ORDER BY t.created_at DESC LIMIT 1`,[context.userId,context.user.email]))[0];if(!customer)throw new Error("No active stay found. Contact Reception.");const today=new Date().toISOString().slice(0,10);if(customer.start_date>today||customer.end_date<today)throw new Error("Service requests are available during an active stay only");const admin=await chooseAdmin();const id=uuid();const status=admin?"assigned":"pending";await queryRows<any>(`INSERT INTO service_requests(id,customer_id,tenancy_id,property_id,apartment_id,service_catalog_id,title,description,category,priority,status,assigned_admin_id,image_urls_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,customer.id,customer.tenancy_id,customer.property_id,customer.apartment_id,data.service_catalog_id||null,data.title.trim().slice(0,255),data.description.trim().slice(0,8000),data.category,data.priority,status,admin?.id||null,JSON.stringify(data.image_urls||[])]);
 const admins=await adminList();for(const a of admins)await queryRows<any>(`INSERT INTO notifications(id,recipient_id,type,title,body,entity_type,entity_id,priority) VALUES(?,?,?,?,?,'service_request',?,?)`,[uuid(),a.id,"service_request",`${data.priority.toUpperCase()}: ${data.title}`,`Customer ${customer.full_name} · ${customer.property_title} · ${customer.apartment_code}${admin?` · Assigned to ${admin.full_name}`:""}`,id,data.priority==="emergency"?"emergency":data.priority==="urgent"?"urgent":"normal"]);
 try{await sendMail(customer.email,"We received your NOVAWORKS service request",`<p>Hello ${customer.full_name},</p><p>We received <b>${data.title}</b>.</p><p>Status: ${admin?`Assigned to ${admin.full_name}`:"Pending assignment"}.</p>`)}catch{}
 const owner=(await rows<any>(`SELECT u.full_name,COALESCE(u.business_email,u.email) email,u.email_notifications_enabled FROM properties p JOIN users u ON u.id=p.owner_id WHERE p.id=?`,[customer.property_id]))[0];if(owner?.email&&owner.email_notifications_enabled!==0){try{await sendMail(owner.email,`Service request — ${customer.property_title}`,`<p>Hello ${owner.full_name||"Owner"},</p><p>A customer at your property requested a service/change.</p><p><b>${data.title}</b><br/>Apartment: ${customer.apartment_code}<br/>Priority: ${data.priority}</p><p>${data.description}</p>`)}catch{}}
 if(data.priority==="urgent"||data.priority==="emergency"){const subject=`${data.priority.toUpperCase()} service request — ${data.title}`;const html=`<h2>${subject}</h2><p><b>Customer:</b> ${customer.full_name}<br/><b>Property:</b> ${customer.property_title}<br/><b>Apartment:</b> ${customer.apartment_code}<br/><b>Assigned:</b> ${admin?.full_name||"Not assigned"}</p><p>${data.description}</p>`;for(const a of admins){try{await sendMail(a.email,subject,html)}catch{}}if(data.priority==="emergency"&&process.env.SMS_EMERGENCY_ENABLED==="true")for(const a of admins.filter(x=>x.phone)){try{await sendSms(a.phone,`${subject}. Assigned: ${admin?.full_name||"pending"}.`,undefined,"service_emergency")}catch{}}}
 await audit(context.userId,"SERVICE_REQUEST_CREATED","service_request",id,null,{priority:data.priority,assigned_admin_id:admin?.id||null});return{id,assigned_admin_id:admin?.id||null,assigned_admin_name:admin?.full_name||null}});

export const updateServiceRequest=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string;status?:Status;admin_response?:string;expected_at?:string|null;assigned_to?:string|null;assigned_admin_id?:string|null})=>d).handler(async({data,context})=>{await assertRoles(context.userId,["it","admin","receptionist"]);const old=(await rows<any>(`SELECT sr.*,c.email customer_email,c.full_name customer_name FROM service_requests sr JOIN customers c ON c.id=sr.customer_id WHERE sr.id=?`,[data.id]))[0];if(!old)throw new Error("Request not found");const assignee=data.assigned_admin_id!==undefined?data.assigned_admin_id:data.assigned_to;const sets:string[]=[];const vals:any[]=[];if(data.status){sets.push("status=?");vals.push(data.status);if(data.status==="completed"){sets.push("completed_at=UTC_TIMESTAMP()")}}if(assignee!==undefined){sets.push("assigned_admin_id=?");vals.push(assignee)}if(data.admin_response!==undefined){sets.push("admin_response=?","responded_at=UTC_TIMESTAMP()","responded_by=?");vals.push(data.admin_response,context.userId)}if(data.expected_at!==undefined){sets.push("expected_at=?");vals.push(data.expected_at||null)}if(sets.length){vals.push(data.id);await queryRows<any>(`UPDATE service_requests SET ${sets.join(',')} WHERE id=?`,vals)}const updated=(await rows<any>(`SELECT * FROM service_requests WHERE id=?`,[data.id]))[0];if(data.admin_response||data.status){try{await sendMail(old.customer_email,"Update on your NOVAWORKS service request",`<p>Hello ${old.customer_name},</p><p>Your request <b>${old.title}</b> is now <b>${updated.status}</b>.</p>${data.admin_response?`<p><b>Response:</b> ${data.admin_response}</p>`:""}${updated.expected_at?`<p><b>Expected action time:</b> ${new Date(updated.expected_at).toLocaleString()}</p>`:""}`)}catch{}}await audit(context.userId,"SERVICE_REQUEST_UPDATED","service_request",data.id,old,updated);return{...updated,assigned_to:updated.assigned_admin_id}});

export const addServiceItem=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{service_request_id:string;description:string;quantity:number;unit_price:number;currency?:string;vendor?:string;receipt_url?:string;owner_chargeable?:boolean})=>d).handler(async({data,context})=>{await assertRoles(context.userId,["it","admin"]);const id=uuid();await queryRows<any>(`INSERT INTO service_items(id,service_request_id,description,quantity,unit_price,currency,vendor,receipt_url,owner_chargeable,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`,[id,data.service_request_id,data.description,Number(data.quantity||1),Number(data.unit_price||0),data.currency||"USD",data.vendor||null,data.receipt_url||null,data.owner_chargeable===false?0:1,context.userId]);await audit(context.userId,"SERVICE_ITEM_ADDED","service_request",data.service_request_id,null,data);return{id}});

export const completeServiceRequest=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string;admin_response?:string})=>d).handler(async({data,context})=>{await assertRoles(context.userId,["it","admin"]);const sr=(await rows<any>(`SELECT sr.*,p.owner_id,p.title property_title,c.full_name customer_name,c.email customer_email FROM service_requests sr JOIN properties p ON p.id=sr.property_id JOIN customers c ON c.id=sr.customer_id WHERE sr.id=?`,[data.id]))[0];if(!sr)throw new Error("Request not found");if(sr.status==="completed")throw new Error("This request is already completed and its owner costs were already posted");const items=await rows<any>(`SELECT * FROM service_items WHERE service_request_id=?`,[data.id]);const chargeable=items.filter(i=>i.owner_chargeable).reduce((s,i)=>s+Number(i.quantity)*Number(i.unit_price),0);await withTransaction(async conn=>{await conn.execute(`UPDATE service_requests SET status='completed',completed_at=UTC_TIMESTAMP(),admin_response=COALESCE(?,admin_response),responded_by=? WHERE id=?`,[data.admin_response||null,context.userId,data.id]);if(sr.owner_id&&chargeable>0){const byCurrency=new Map<string,number>();for(const i of items.filter(x=>x.owner_chargeable))byCurrency.set(i.currency,(byCurrency.get(i.currency)||0)+Number(i.quantity)*Number(i.unit_price));for(const [currency,amount] of byCurrency)await conn.execute(`INSERT INTO owner_ledger(id,owner_id,property_id,tenancy_id,service_request_id,entry_type,description,amount,currency,direction,created_by) VALUES(?,?,?,?,?,'maintenance',?,?, 'debit',?)`,[uuid(),sr.owner_id,sr.property_id,sr.tenancy_id,sr.id,`Maintenance: ${sr.title}`,amount,currency,context.userId])}});try{await sendMail(sr.customer_email,"Your NOVAWORKS service request was completed",`<p>Hello ${sr.customer_name},</p><p><b>${sr.title}</b> has been marked completed.</p>${data.admin_response?`<p>${data.admin_response}</p>`:""}`)}catch{}await audit(context.userId,"SERVICE_REQUEST_COMPLETED","service_request",data.id,null,{owner_chargeable_total:chargeable});return{ok:true,owner_chargeable_total:chargeable}});

export const listAssignableStaff=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{await assertRoles(context.userId,["it","admin","receptionist"]);return rows<any>(`SELECT u.id,u.full_name name,u.email,COUNT(sr.id) pending_count FROM users u JOIN user_roles ur ON ur.user_id=u.id AND ur.role='admin' LEFT JOIN service_requests sr ON sr.assigned_admin_id=u.id AND sr.status IN('pending','assigned','in_progress','awaiting_owner') WHERE u.active=1 GROUP BY u.id ORDER BY pending_count,u.full_name`)});
