import { createServerFn } from "@tanstack/react-start";
import { requireMysqlAuth } from "@/integrations/mysql/auth-middleware";
import { rows, audit } from "./db-utils.server";
import { queryRows } from "./mysql.server";

async function it(context:any){ if(!context.roles.includes("it")) throw new Error("IT only"); }
export const listMailRecipients=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{await it(context); const users=await rows<any>(`SELECT u.id,u.full_name,u.email,u.business_email,u.active,u.email_notifications_enabled,u.created_at,GROUP_CONCAT(ur.role ORDER BY ur.role) roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC`); const subscribers=await rows<any>(`SELECT id,full_name,email,verified,notify,marketing_consent,unsubscribed_at,created_at FROM subscribers ORDER BY created_at DESC`); return {users:users.map(x=>({...x,roles:String(x.roles||"").split(',').filter(Boolean)})),subscribers};});
export const setUserMailEnabled=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string;enabled:boolean})=>d).handler(async({data,context})=>{await it(context);await queryRows<any>(`UPDATE users SET email_notifications_enabled=? WHERE id=?`,[data.enabled?1:0,data.id]);await audit(context.userId,"USER_MAIL_TOGGLED","user",data.id,null,{enabled:data.enabled});return{ok:true}});
export const updateSubscriber=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string;full_name?:string;notify?:boolean;marketing_consent?:boolean})=>d).handler(async({data,context})=>{await it(context);await queryRows<any>(`UPDATE subscribers SET full_name=COALESCE(?,full_name),notify=COALESCE(?,notify),marketing_consent=COALESCE(?,marketing_consent),unsubscribed_at=CASE WHEN COALESCE(?,notify)=1 THEN NULL ELSE COALESCE(unsubscribed_at,UTC_TIMESTAMP()) END WHERE id=?`,[data.full_name??null,data.notify===undefined?null:(data.notify?1:0),data.marketing_consent===undefined?null:(data.marketing_consent?1:0),data.notify===undefined?null:(data.notify?1:0),data.id]);return{ok:true}});
export const deleteSubscriber=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string})=>d).handler(async({data,context})=>{await it(context);await queryRows<any>(`DELETE FROM subscribers WHERE id=?`,[data.id]);return{ok:true}});
