import { createServerFn } from "@tanstack/react-start";
import { rows, uuid, audit, assertRoles, requireFeature } from "./db-utils.server";
import { queryRows } from "./mysql.server";
import { sendMail } from "./mailer.server";
import { requireMysqlAuth } from "@/integrations/mysql/auth-middleware";

async function chooseAdmin(){return (await rows<any>(`SELECT u.id,u.full_name,u.email,COUNT(v.id) pending_count FROM users u JOIN user_roles ur ON ur.user_id=u.id AND ur.role='admin' LEFT JOIN visit_requests v ON v.assigned_admin_id=u.id AND v.status IN('requested','assigned','confirmed') WHERE u.active=1 GROUP BY u.id ORDER BY pending_count ASC,COALESCE(MAX(v.created_at),'1970-01-01') ASC,u.created_at ASC LIMIT 1`))[0]??null}
async function admins(){return rows<any>(`SELECT DISTINCT u.id,u.full_name,u.email FROM users u JOIN user_roles ur ON ur.user_id=u.id WHERE ur.role='admin' AND u.active=1`)}

export const createVisitRequest=createServerFn({method:"POST"}).validator((d:{property_id:string;apartment_id?:string;name:string;email:string;phone:string;requested_for:string;notes?:string})=>d).handler(async({data})=>{
  await requireFeature("visit_requests");
  if(!data.name?.trim()||!/^\S+@\S+\.\S+$/.test(data.email||"")||!data.phone?.trim()||!data.property_id||!data.requested_for)throw new Error("Complete the visit request details");
  const property=(await rows<any>(`SELECT id,title,address,city,district,country,lat,lng FROM properties WHERE id=? AND status='active'`,[data.property_id]))[0];if(!property)throw new Error("Property is not available");
  let unit:any=null;if(data.apartment_id){unit=(await rows<any>(`SELECT id,code,name,property_id FROM apartments WHERE id=? AND property_id=? LIMIT 1`,[data.apartment_id,property.id]))[0];if(!unit)throw new Error("Selected unit is not part of this property");}
  const admin=await chooseAdmin();const id=uuid();
  const customer=(await rows<any>(`SELECT id FROM customers WHERE LOWER(email)=LOWER(?) ORDER BY created_at DESC LIMIT 1`,[data.email]))[0];
  await queryRows<any>(`INSERT INTO visit_requests(id,property_id,apartment_id,customer_id,requester_name,requester_email,requester_phone,requested_for,notes,assigned_admin_id,status) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[id,property.id,data.apartment_id||null,customer?.id||null,data.name.trim(),data.email.trim().toLowerCase(),data.phone.trim(),new Date(data.requested_for),data.notes||null,admin?.id||null,admin?"assigned":"requested"]);
  const all=await admins();for(const a of all){await queryRows<any>(`INSERT INTO staff_notifications(id,user_id,type,title,message,reference_id) VALUES(?,?,?,?,?,?)`,[uuid(),a.id,"visit_request","New property visit request",`${property.title}${unit?.code?` · ${unit.code}`:""} · ${data.name} · Assigned to ${admin?.full_name||"unassigned"}`,id]);try{await sendMail(a.email,"New NOVAWORKS visit request",`<h2>New property visit</h2><p><b>Property:</b> ${property.title}${unit?.code?`<br/><b>Requested unit:</b> ${unit.code}${unit.name?` — ${unit.name}`:""}`:""}<br/><b>Location:</b> ${[property.address,property.district,property.city,property.country].filter(Boolean).join(", ")}<br/><b>Visitor:</b> ${data.name}<br/><b>Requested:</b> ${new Date(data.requested_for).toLocaleString()}<br/><b>Assigned admin:</b> ${admin?.full_name||"Not assigned"}</p><p>${data.notes||""}</p>`)}catch{}}
  try{await sendMail(data.email,"NOVAWORKS received your visit request",`<p>Hello ${data.name},</p><p>Your visit request for <b>${property.title}</b>${unit?.code?` — unit <b>${unit.code}</b>`:""} was received for ${new Date(data.requested_for).toLocaleString()}.</p><p><b>Property location:</b> ${[property.address,property.district,property.city,property.country].filter(Boolean).join(", ") || "Location available on the property page"}</p><p>Our team will confirm the appointment and send you the name, phone number and email address of your assigned NOVAWORKS contact.</p>`)}catch{}
  await audit(null,"VISIT_REQUESTED","visit_request",id,null,{property_id:property.id,apartment_id:unit?.id||null,apartment_code:unit?.code||null,assigned_admin_id:admin?.id||null});return{id,assigned_admin_name:admin?.full_name||null};
});

export const listVisitRequests=createServerFn({method:"GET"}).middleware([requireMysqlAuth]).handler(async({context})=>{await assertRoles(context.userId,["it","admin"]);return rows<any>(`SELECT v.*,p.title property_title,a.code apartment_code,u.full_name assigned_admin_name,CASE WHEN v.requested_for < DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY) AND v.status NOT IN('completed','cancelled','expired','no_show') THEN 1 ELSE 0 END overdue FROM visit_requests v JOIN properties p ON p.id=v.property_id LEFT JOIN apartments a ON a.id=v.apartment_id LEFT JOIN users u ON u.id=v.assigned_admin_id ORDER BY overdue DESC, v.requested_for ASC`)});

export const updateVisitRequest=createServerFn({method:"POST"}).middleware([requireMysqlAuth]).validator((d:{id:string;status?:"assigned"|"confirmed"|"completed"|"cancelled"|"expired"|"no_show";assigned_admin_id?:string|null})=>d).handler(async({data,context})=>{
 await assertRoles(context.userId,["it","admin"]);
 const old=(await rows<any>(`SELECT v.*,p.title property_title,a.code apartment_code,u.full_name assigned_admin_name,u.phone assigned_admin_phone,COALESCE(u.business_email,u.email) assigned_admin_email FROM visit_requests v JOIN properties p ON p.id=v.property_id LEFT JOIN apartments a ON a.id=v.apartment_id LEFT JOIN users u ON u.id=v.assigned_admin_id WHERE v.id=?`,[data.id]))[0];
 if(!old)throw new Error("Visit not found");
 const sets:string[]=[];const vals:any[]=[];if(data.status){sets.push("status=?");vals.push(data.status);if(data.status==="completed")sets.push("completed_at=UTC_TIMESTAMP()")};if(data.assigned_admin_id!==undefined){sets.push("assigned_admin_id=?");vals.push(data.assigned_admin_id)};if(!sets.length)return{ok:true};vals.push(data.id);await queryRows<any>(`UPDATE visit_requests SET ${sets.join(",")} WHERE id=?`,vals);
 const updated=(await rows<any>(`SELECT v.*,p.title property_title,a.code apartment_code,u.full_name assigned_admin_name,u.phone assigned_admin_phone,COALESCE(u.business_email,u.email) assigned_admin_email FROM visit_requests v JOIN properties p ON p.id=v.property_id LEFT JOIN apartments a ON a.id=v.apartment_id LEFT JOIN users u ON u.id=v.assigned_admin_id WHERE v.id=?`,[data.id]))[0];
 try{const {brandedEmail}=await import("./mailer.server"); await sendMail(old.requester_email,`Your NOVAWORKS visit is ${updated.status}`,brandedEmail(`Visit ${updated.status}`,`<p>Hello ${old.requester_name},</p><p>Your visit for <b>${old.property_title}</b>${old.apartment_code?` — unit <b>${old.apartment_code}</b>`:""} is now <b>${updated.status}</b>.</p><p><b>Scheduled:</b> ${new Date(updated.requested_for).toLocaleString()}</p>${updated.assigned_admin_name?`<div style="padding:14px;background:#f7f4ec;border-radius:10px"><b>Your NOVAWORKS contact</b><br/>${updated.assigned_admin_name}${updated.assigned_admin_email?`<br/>Email: <a href="mailto:${updated.assigned_admin_email}">${updated.assigned_admin_email}</a>`:""}${updated.assigned_admin_phone?`<br/>Phone: <a href="tel:${updated.assigned_admin_phone}">${updated.assigned_admin_phone}</a>`:""}</div>`:""}<p>If you need to change the appointment, simply reply to this email.</p>`));}catch{}
 await audit(context.userId,"VISIT_STATUS_CHANGED","visit_request",data.id,old,updated);return updated;
});
