import { createFileRoute, Link } from "@tanstack/react-router";
import { Award, Users, Building2, Sparkles, ArrowRight, Quote } from "lucide-react";
import { getContactContent } from "@/lib/contact-content.functions";
import { ProgressiveImage } from "@/components/site/ProgressiveImage";

export const Route = createFileRoute("/_site/about")({
  head: () => ({ meta: [{ title: "Who We Are — NOVAWORKS Real Estate Rwanda" }, { name: "description", content: "Meet NOVAWORKS leadership and team and learn how we manage exceptional property in Rwanda." }] }),
  loader: () => getContactContent(),
  component: AboutPage,
});
function AboutPage(){const {ceo,team}=Route.useLoaderData();return <div>
  <section className="relative bg-noir-deep text-white py-24 overflow-hidden"><div className="absolute inset-0 opacity-20"><ProgressiveImage src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=2000&q=80" alt="" priority width={1600} height={900} sizes="100vw" className="w-full h-full object-cover" containerClassName="w-full h-full"/></div><div className="container-luxe relative max-w-3xl"><div className="text-xs uppercase tracking-[0.2em] text-gold">Who We Are</div><h1 className="mt-4 font-display text-5xl md:text-7xl">A discreet atelier for prime property.</h1><p className="mt-6 text-white/70 text-lg">NOVAWORKS is a Rwanda-rooted real estate company. We curate, broker and manage exceptional properties with a focus on trust, service and durable value.</p></div></section>
  <section className="py-20"><div className="container-luxe"><div className="text-center max-w-2xl mx-auto"><div className="text-xs uppercase tracking-[0.2em] text-gold">Leadership & Team</div><h2 className="mt-3 font-display text-4xl md:text-5xl">The people behind NOVAWORKS</h2></div><div className="mt-14 max-w-5xl mx-auto"><div className="relative grid md:grid-cols-[400px_1fr] gap-10 bg-card border border-gold/30 rounded-2xl p-8 md:p-10 shadow-xl items-center"><ProgressiveImage src={ceo.image} alt={ceo.name} width={800} height={1000} sizes="(max-width:768px) 100vw,400px" className="w-full aspect-[4/5] rounded-xl object-cover object-top" containerClassName="rounded-xl"/><div><div className="text-xs uppercase tracking-[0.2em] text-gold">{ceo.title}</div><div className="mt-2 font-display text-3xl md:text-4xl">{ceo.name}</div><Quote className="w-8 h-8 text-gold/60 mt-5"/><blockquote className="mt-2 font-display italic text-xl leading-relaxed">“{ceo.quote}”</blockquote>{ceo.since&&<div className="mt-5 text-sm text-muted-foreground">{ceo.since}</div>}</div></div></div>{team.length>0&&<div className="mt-16 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{team.map(m=><div key={m.name+m.image} className="bg-card border border-gold/20 rounded-2xl p-6 text-center"><ProgressiveImage src={m.image} alt={m.name} width={400} height={400} sizes="(max-width:640px) 70vw,240px" className="w-32 h-32 mx-auto rounded-full object-cover" containerClassName="mx-auto w-32 h-32 rounded-full ring-2 ring-gold/30"/><div className="mt-5 font-display text-xl">{m.name}</div><div className="mt-1 text-xs uppercase tracking-[0.18em] text-gold">{m.role}</div></div>)}</div>}</div></section>
  <section className="py-20 bg-muted/40"><div className="container-luxe"><div className="text-center max-w-2xl mx-auto"><div className="text-xs uppercase tracking-[0.2em] text-gold">Our Values</div><h2 className="mt-3 font-display text-4xl">What guides every transaction.</h2></div><div className="mt-12 grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{[{i:Award,t:"Excellence",d:"Uncompromising standards on every listing, meeting and detail."},{i:Users,t:"Discretion",d:"Confidentiality is the default for clients and properties alike."},{i:Building2,t:"Stewardship",d:"We care for assets with long-term owner value in mind."},{i:Sparkles,t:"Service",d:"Clear communication and dependable follow-through at every stage."}].map(v=><div key={v.t} className="bg-card border border-border rounded-xl p-6 text-center"><div className="w-12 h-12 mx-auto rounded-lg bg-gold/10 text-gold flex items-center justify-center"><v.i className="w-6 h-6"/></div><div className="mt-4 font-display text-xl">{v.t}</div><div className="mt-2 text-sm text-muted-foreground">{v.d}</div></div>)}</div></div></section>
  <section className="py-24"><div className="container-luxe max-w-3xl text-center"><Quote className="w-10 h-10 text-gold mx-auto"/><p className="mt-6 font-display text-3xl md:text-4xl italic">“Real estate is about the lives that unfold inside the walls.”</p><div className="mt-6 text-sm text-muted-foreground">NOVAWORKS principle</div><Link to="/contact" className="mt-10 inline-flex items-center gap-2 bg-noir-deep text-white px-6 py-3 rounded-md text-sm font-medium">Speak with our team <ArrowRight className="w-4 h-4"/></Link></div></section>
</div>}
