import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, Mail, RefreshCw } from "lucide-react";
export const Route=createFileRoute("/auth/verify")({validateSearch:(s:Record<string,unknown>)=>({email:String(s.email||"")}),component:VerifyPage});
function VerifyPage(){const {email}=Route.useSearch();const nav=useNavigate();const [code,setCode]=useState(Array(6).fill(""));const [error,setError]=useState<string|null>(null);const [info,setInfo]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [cooldown,setCooldown]=useState(0);const inputs=useRef<(HTMLInputElement|null)[]>([]);
 useEffect(()=>{if(cooldown>0){const t=setTimeout(()=>setCooldown(cooldown-1),1000);return()=>clearTimeout(t)}},[cooldown]);
 const resend=async()=>{setError(null);const r=await fetch("/api/auth/otp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});if(r.ok){setInfo("A fresh 6-digit code was sent.");setCooldown(45)}};
 useEffect(()=>{if(email)resend()},[email]);
 const verify=async()=>{const token=code.join("");if(token.length!==6)return;setBusy(true);const r=await fetch("/api/auth/otp",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code:token})});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Invalid code");return;}localStorage.setItem("novaworks_session",d.token);nav({to:"/auth/welcome",search:{to:""}} as any)};
 useEffect(()=>{if(code.every(Boolean)&&!busy)verify()},[code]);
 return <div className="flex min-h-screen items-center justify-center px-6"><div className="w-full max-w-md rounded-2xl bg-white border p-8 shadow-xl"><div className="mx-auto h-14 w-14 rounded-full bg-gold/15 text-gold flex items-center justify-center"><Mail/></div><h1 className="font-display text-3xl text-center mt-5">Verify your email</h1><p className="text-sm text-noir/60 text-center mt-2">Enter the six digits sent to <b>{email}</b>.</p>{error&&<div className="mt-4 bg-red-50 text-red-700 p-3 rounded">{error}</div>}{info&&<div className="mt-4 bg-emerald-50 text-emerald-700 p-3 rounded">{info}</div>}<div className="flex gap-2 mt-6" onPaste={e=>{const t=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);if(t){e.preventDefault();setCode(Array(6).fill("").map((_,i)=>t[i]||""))}}}>{code.map((d,i)=><input key={i} ref={el=>{inputs.current[i]=el}} value={d} maxLength={1} inputMode="numeric" onChange={e=>{const x=e.target.value.replace(/\D/g,"").slice(-1);setCode(c=>c.map((v,j)=>j===i?x:v));if(x&&i<5)inputs.current[i+1]?.focus()}} className="w-12 h-14 border rounded text-center text-2xl"/>)}</div><button onClick={verify} disabled={busy} className="w-full mt-5 bg-gold py-3 rounded font-semibold inline-flex justify-center items-center gap-2">{busy?"Verifying…":<>Verify <ArrowRight className="h-4 w-4"/></>}</button><button onClick={resend} disabled={cooldown>0} className="w-full mt-3 text-sm text-gold"><RefreshCw className="inline h-3 w-3"/> {cooldown?`Resend in ${cooldown}s`:"Resend code"}</button><div className="text-center mt-5 text-xs"><Link to="/auth">Back to sign in</Link></div></div></div>}
