import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useMemo,useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Mail,MailX,Search,Trash2,UserRound,UsersRound } from "lucide-react";
import { DashboardShell,Panel } from "@/components/dashboard/DashboardShell";
import { RoleGate } from "@/components/dashboard/RoleGate";
import { shellForStaff } from "@/components/dashboard/nav-config";
import { useAuth } from "@/lib/use-auth";
import { listMailRecipients,setUserMailEnabled,updateSubscriber,deleteSubscriber } from "@/lib/subscribers.functions";
import { toast } from "sonner";
export const Route=createFileRoute("/_authenticated/dashboard/it/subscribers")({component:()=> <RoleGate allow={["it"]} exclusive><Page/></RoleGate>});
function Page(){const {roles}=useAuth();const shell=shellForStaff(roles);const load=useServerFn(listMailRecipients),toggleUser=useServerFn(setUserMailEnabled),upd=useServerFn(updateSubscriber),del=useServerFn(deleteSubscriber);const [data,setData]=useState<any>({users:[],subscribers:[]});const [q,setQ]=useState("");const [role,setRole]=useState("all");const refresh=()=>load().then(setData);useEffect(()=>{refresh()},[]);const users=useMemo(()=>data.users.filter((u:any)=>(role==='all'||u.roles.includes(role))&&`${u.full_name} ${u.email}`.toLowerCase().includes(q.toLowerCase())),[data,q,role]);return <DashboardShell title="Users & Subscribers" subtitle="IT-only control of accounts, subscribers and email delivery" role={shell.role} nav={shell.nav}><Panel title="Registered users"><div className="mb-4 flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-noir/35"/><input className="input-luxe pl-9" placeholder="Search users…" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input-luxe max-w-44" value={role} onChange={e=>setRole(e.target.value)}><option value="all">All roles</option>{['it','admin','receptionist','owner','agent','customer'].map(x=><option key={x}>{x}</option>)}</select></div><div className="space-y-2">{users.map((u:any)=><div key={u.id} className="flex items-center gap-3 rounded-xl border p-3"><UserRound className="h-5 w-5"/><div className="min-w-0 flex-1"><b>{u.full_name}</b><div className="text-xs text-noir/50">{u.email} · {u.roles.join(', ')||'no role'}</div></div><button title={u.email_notifications_enabled?'Hold email':'Enable email'} onClick={async()=>{await toggleUser({data:{id:u.id,enabled:!u.email_notifications_enabled}});toast.success('Email preference updated');refresh()}} className={`rounded-lg p-2 ${u.email_notifications_enabled?'text-emerald-600':'text-rose-600 bg-rose-50'}`}>{u.email_notifications_enabled?<Mail className="h-5 w-5"/>:<MailX className="h-5 w-5"/>}</button></div>)}</div></Panel><Panel title="Newsletter subscribers"><div className="space-y-2">{data.subscribers.map((s:any)=><div key={s.id} className="flex items-center gap-3 rounded-xl border p-3"><UsersRound className="h-5 w-5"/><div className="min-w-0 flex-1"><b>{s.full_name||'Subscriber'}</b><div className="text-xs text-noir/50">{s.email} · {s.verified?'verified':'unverified'}</div></div><button title={s.notify?'Hold notifications':'Resume notifications'} onClick={async()=>{await upd({data:{id:s.id,notify:!s.notify}});refresh()}} className={`rounded-lg p-2 ${s.notify?'text-emerald-600':'text-rose-600 bg-rose-50'}`}>{s.notify?<Mail className="h-5 w-5"/>:<MailX className="h-5 w-5"/>}</button><button title="Delete subscriber" onClick={async()=>{if(confirm(`Delete ${s.email}?`)){await del({data:{id:s.id}});refresh()}}} className="rounded-lg p-2 text-rose-600"><Trash2 className="h-5 w-5"/></button></div>)}</div></Panel></DashboardShell>}
