import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Wrench, AlertCircle, Clock, CheckCircle2, Search, X, Send, UserCheck, LayoutDashboard, Building2, MessageSquare, Bell, Plus, ReceiptText, Trash2 } from "lucide-react";
import { DashboardShell, StatCard, Panel } from "@/components/dashboard/DashboardShell";
import { RoleGate } from "@/components/dashboard/RoleGate";
import { useAuth } from "@/lib/use-auth";
import { navForRoles } from "@/components/dashboard/nav-config";
import { listAllServiceRequests, updateServiceRequest, listAssignableStaff, addServiceItem, completeServiceRequest } from "@/lib/service-requests.functions";

export const Route = createFileRoute("/_authenticated/dashboard/service-requests")({
  head: () => ({ meta: [{ title: "Service Requests — NOVAWORKS" }] }),
  component: () => <RoleGate allow={["admin", "it", "receptionist"]}><StaffServiceRequestsPage /></RoleGate>,
});

const STATUS_BADGE: Record<string, string> = {
  pending: "bg-amber-50 text-amber-700", assigned: "bg-violet-50 text-violet-700",
  in_progress: "bg-sky-50 text-sky-700", awaiting_owner: "bg-indigo-50 text-indigo-700",
  completed: "bg-emerald-50 text-emerald-700", cancelled: "bg-noir/5 text-noir/60",
};
const PRIORITY_BADGE: Record<string, string> = {
  low: "bg-noir/5 text-noir/70", medium: "bg-blue-50 text-blue-700", high: "bg-orange-50 text-orange-700",
  urgent: "bg-rose-50 text-rose-700 ring-1 ring-rose-200 animate-pulse", emergency: "bg-red-600 text-white ring-2 ring-red-200 animate-pulse",
};

function StaffServiceRequestsPage() {
  const { primaryRole, roles } = useAuth(); const role = (primaryRole ?? "admin") as any; const shell = navForRoles(roles); const qc = useQueryClient();
  const list = useServerFn(listAllServiceRequests), listStaff = useServerFn(listAssignableStaff), update = useServerFn(updateServiceRequest);
  const addItem = useServerFn(addServiceItem), complete = useServerFn(completeServiceRequest);
  const { data: requests = [], isLoading } = useQuery({ queryKey: ["all-service-requests"], queryFn: () => list() });
  const { data: staff = [] } = useQuery({ queryKey: ["assignable-staff"], queryFn: () => listStaff() });
  const [selected, setSelected] = useState<any | null>(null), [q, setQ] = useState(""), [statusFilter, setStatusFilter] = useState("all"), [priorityFilter, setPriorityFilter] = useState("all");
  const refresh = async () => { await qc.invalidateQueries({ queryKey: ["all-service-requests"] }); const fresh = await list(); if (selected) setSelected(fresh.find((r:any)=>r.id===selected.id) ?? null); };
  const updateMut = useMutation({ mutationFn: (d:any) => update({ data: d }), onSuccess: async()=>{toast.success("Request updated"); await refresh();}, onError:(e:any)=>toast.error(e.message??"Failed") });
  const addMut = useMutation({ mutationFn:(d:any)=>addItem({data:d}), onSuccess:async()=>{toast.success("Cost item added");await refresh();},onError:(e:any)=>toast.error(e.message??"Failed")});
  const completeMut = useMutation({ mutationFn:(d:any)=>complete({data:d}),onSuccess:async(r:any)=>{toast.success(`Completed. Owner-chargeable cost: ${Number(r.owner_chargeable_total||0).toFixed(2)}`);await refresh();},onError:(e:any)=>toast.error(e.message??"Failed")});
  const filtered=useMemo(()=>requests.filter((r:any)=>{if(statusFilter!=="all"&&r.status!==statusFilter)return false;if(priorityFilter!=="all"&&r.priority!==priorityFilter)return false;if(q&&!`${r.title} ${r.description} ${r.customers?.full_name??""} ${r.customers?.email??""}`.toLowerCase().includes(q.toLowerCase()))return false;return true}),[requests,q,statusFilter,priorityFilter]);
  const stats={total:requests.length,urgent:requests.filter((r:any)=>["urgent","emergency"].includes(r.priority)&&r.status!=="completed").length,pending:requests.filter((r:any)=>["pending","assigned"].includes(r.status)).length,in_progress:requests.filter((r:any)=>r.status==="in_progress").length};
  return <DashboardShell title="Service Requests" subtitle="Assign work, record parts/labour, notify customers, and post owner deductions" role={shell.role} nav={shell.nav}>
    <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatCard icon={MessageSquare} label="Total" value={String(stats.total)}/><StatCard icon={AlertCircle} label="Urgent / emergency" value={String(stats.urgent)}/><StatCard icon={Clock} label="Waiting" value={String(stats.pending)}/><StatCard icon={CheckCircle2} label="In progress" value={String(stats.in_progress)}/></div>
    <div className="mt-6 flex flex-wrap gap-3"><div className="flex-1 min-w-[240px] relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-noir/40"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customer, title, description…" className="w-full rounded-lg bg-white border border-noir/10 pl-9 pr-3 py-2.5 text-sm"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded-lg bg-white border border-noir/10 px-3 py-2.5 text-sm"><option value="all">All status</option>{Object.keys(STATUS_BADGE).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)} className="rounded-lg bg-white border border-noir/10 px-3 py-2.5 text-sm"><option value="all">All priority</option>{["emergency","urgent","high","medium","low"].map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="mt-4 space-y-3">{isLoading&&<p className="text-sm text-noir/50">Loading…</p>}{!isLoading&&filtered.length===0&&<div className="rounded-2xl bg-white border border-noir/5 p-10 text-center text-sm text-noir/50">No requests match.</div>}{filtered.map((r:any)=>{const assignee=staff.find((s:any)=>s.id===r.assigned_to);const itemTotal=(r.service_items||[]).reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unit_price),0);return <article key={r.id} className={`rounded-2xl bg-white border p-5 shadow-sm hover:shadow-md transition cursor-pointer ${["urgent","emergency"].includes(r.priority)&&r.status!=="completed"?"border-rose-200":"border-noir/5"}`} onClick={()=>setSelected(r)}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg">{r.title}</h3><span className={`text-[11px] px-2 py-0.5 rounded-md ${STATUS_BADGE[r.status]||"bg-noir/5"}`}>{r.status?.replaceAll("_"," ")}</span><span className={`text-[11px] px-2 py-0.5 rounded-md capitalize ${PRIORITY_BADGE[r.priority]}`}>{r.priority}</span></div><p className="text-sm text-noir/70 mt-1 line-clamp-2">{r.description}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-noir/50"><span>{r.customers?.full_name}</span><span>{r.customers?.properties?.title} · {r.customers?.apartment_no}</span>{assignee&&<span className="inline-flex items-center gap-1 text-violet-700"><UserCheck className="h-3 w-3"/>{assignee.name}</span>}{itemTotal>0&&<span className="font-medium text-noir/70">Recorded cost {itemTotal.toFixed(2)}</span>}</div></div></div></article>})}</div>
    {selected&&<ManageModal request={selected} staff={staff} canCost={role==="it"||role==="admin"} onClose={()=>setSelected(null)} onSave={d=>updateMut.mutate({id:selected.id,...d})} onAddItem={d=>addMut.mutate({service_request_id:selected.id,...d})} onComplete={reply=>completeMut.mutate({id:selected.id,admin_response:reply})} saving={updateMut.isPending||addMut.isPending||completeMut.isPending}/>} 
  </DashboardShell>;
}

function ManageModal({request,staff,canCost,onClose,onSave,onAddItem,onComplete,saving}:{request:any;staff:any[];canCost:boolean;onClose:()=>void;onSave:(d:any)=>void;onAddItem:(d:any)=>void;onComplete:(reply:string)=>void;saving:boolean}){
  const [status,setStatus]=useState(request.status),[assignedTo,setAssignedTo]=useState(request.assigned_to??""),[reply,setReply]=useState(request.admin_response??""),[expectedAt,setExpectedAt]=useState(request.expected_at?String(request.expected_at).slice(0,16):"");
  const [item,setItem]=useState({description:"",quantity:1,unit_price:0,currency:"USD",vendor:"",owner_chargeable:true});
  const total=(request.service_items||[]).reduce((s:number,i:any)=>s+Number(i.quantity)*Number(i.unit_price),0);
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm" onClick={onClose}><div className="w-full max-w-3xl rounded-2xl bg-white shadow-2xl max-h-[92vh] overflow-y-auto" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><header className="flex items-center justify-between px-6 py-4 border-b sticky top-0 bg-white z-10"><div><h2 className="font-display text-xl">{request.title}</h2><p className="text-xs text-noir/50">{request.customers?.full_name} · {request.customers?.properties?.title} · {request.customers?.apartment_no}</p></div><button onClick={onClose}><X className="h-5 w-5"/></button></header><div className="p-6 space-y-5"><Panel title="Customer request"><p className="text-sm whitespace-pre-line">{request.description}</p></Panel><div className="grid sm:grid-cols-2 gap-4"><label className="text-xs font-medium">Status<select className="input-luxe mt-1 w-full" value={status} onChange={e=>setStatus(e.target.value)}>{Object.keys(STATUS_BADGE).map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label className="text-xs font-medium">Assigned admin<select className="input-luxe mt-1 w-full" value={assignedTo} onChange={e=>setAssignedTo(e.target.value)}><option value="">Unassigned</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} · {s.pending_count} open</option>)}</select></label></div>
      {canCost&&<Panel title="Repair items & cost" subtitle="Owner-chargeable items are deducted from the owner's ledger only when the request is completed"><div className="space-y-2">{(request.service_items||[]).map((i:any)=><div key={i.id} className="grid grid-cols-[1fr_auto] gap-3 rounded-lg bg-noir/[.03] p-3 text-sm"><div><div className="font-medium">{i.description}</div><div className="text-xs text-noir/50">{Number(i.quantity)} × {Number(i.unit_price).toFixed(2)} {i.currency}{i.vendor?` · ${i.vendor}`:""}{i.owner_chargeable===0?" · not charged to owner":""}</div></div><div className="font-semibold">{(Number(i.quantity)*Number(i.unit_price)).toFixed(2)} {i.currency}</div></div>)}{!(request.service_items||[]).length&&<p className="text-xs text-noir/45">No parts or labour recorded yet.</p>}</div><div className="grid sm:grid-cols-6 gap-2 mt-4"><input className="input-luxe sm:col-span-2" placeholder="Item / labour" value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/><input className="input-luxe" type="number" min="0.01" step="0.01" value={item.quantity} onChange={e=>setItem({...item,quantity:Number(e.target.value)})}/><input className="input-luxe" type="number" min="0" step="0.01" value={item.unit_price} onChange={e=>setItem({...item,unit_price:Number(e.target.value)})}/><input className="input-luxe" placeholder="Currency" maxLength={3} value={item.currency} onChange={e=>setItem({...item,currency:e.target.value.toUpperCase()})}/><input className="input-luxe" placeholder="Vendor" value={item.vendor} onChange={e=>setItem({...item,vendor:e.target.value})}/></div><label className="flex items-center gap-2 text-xs mt-3"><input type="checkbox" checked={item.owner_chargeable} onChange={e=>setItem({...item,owner_chargeable:e.target.checked})}/>Deduct this cost from owner proceeds</label><div className="mt-3 flex justify-between items-center"><button disabled={!item.description.trim()||saving} onClick={()=>{onAddItem(item);setItem({description:"",quantity:1,unit_price:0,currency:"USD",vendor:"",owner_chargeable:true})}} className="inline-flex items-center gap-2 px-3 py-2 rounded-lg border text-sm"><Plus className="h-4 w-4"/>Add item</button><div className="text-sm"><ReceiptText className="inline h-4 w-4 mr-1"/>Recorded total <b>{total.toFixed(2)}</b></div></div></Panel>}
      <div className="grid sm:grid-cols-[1fr_220px] gap-3"><label className="block text-xs font-medium">Reply / completion note<textarea className="input-luxe w-full min-h-28 mt-1" value={reply} onChange={e=>setReply(e.target.value)} placeholder="This is emailed to the customer and shown in their request history."/></label><label className="block text-xs font-medium">Expected action time<input type="datetime-local" className="input-luxe w-full mt-1" value={expectedAt} onChange={e=>setExpectedAt(e.target.value)}/></label></div></div><footer className="flex flex-wrap items-center justify-end gap-2 px-6 py-4 border-t sticky bottom-0 bg-white"><button onClick={onClose} className="px-4 py-2 rounded-lg text-sm hover:bg-noir/5">Cancel</button><button disabled={saving} onClick={()=>onSave({status,assigned_to:assignedTo||null,admin_response:reply,expected_at:expectedAt||null})} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm bg-noir-deep text-white"><Send className="h-4 w-4"/>Save & notify</button>{canCost&&request.status!=="completed"&&<button disabled={saving} onClick={()=>onComplete(reply)} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm bg-emerald-600 text-white"><CheckCircle2 className="h-4 w-4"/>Complete & post costs</button>}</footer></div></div>;
}
