/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteInvestorsRouteImport } from './routes/_site.investors'
import { Route as SiteListPropertyRouteImport } from './routes/_site.list-property'
import { Route as SiteLuxuryAccessRouteImport } from './routes/_site.luxury-access'
import { Route as SitePortfolioRouteImport } from './routes/_site.portfolio'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SiteVerifyAccessRouteImport } from './routes/_site.verify-access'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFeaturesRouteImport } from './routes/api/features'
import { Route as ApiNotificationsCountRouteImport } from './routes/api/notifications-count'
import { Route as ApiPropertyTypesRouteImport } from './routes/api/property-types'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthChangePasswordRouteImport } from './routes/auth.change-password'
import { Route as AuthPasswordResetRouteImport } from './routes/auth.password-reset'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthWelcomeRouteImport } from './routes/auth.welcome'
import { Route as AuthenticatedDashboardAgentRouteImport } from './routes/_authenticated/dashboard.agent'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard.bookings'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardOwnerRouteImport } from './routes/_authenticated/dashboard.owner'
import { Route as AuthenticatedDashboardReceptionistRouteImport } from './routes/_authenticated/dashboard.receptionist'
import { Route as AuthenticatedDashboardServiceCatalogRouteImport } from './routes/_authenticated/dashboard.service-catalog'
import { Route as AuthenticatedDashboardServiceRequestsRouteImport } from './routes/_authenticated/dashboard.service-requests'
import { Route as SiteCustomerPassTokenRouteImport } from './routes/_site.customer-pass.$token'
import { Route as SitePortfolioVideosRouteImport } from './routes/_site.portfolio.videos'
import { Route as SitePropertiesIndexRouteImport } from './routes/_site.properties.index'
import { Route as SitePropertiesSlugRouteImport } from './routes/_site.properties.$slug'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth.change-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth.me'
import { Route as ApiAuthOtpRouteImport } from './routes/api/auth.otp'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth.signup'
import { Route as ApiCustomerAccessRouteImport } from './routes/api/customer.access'
import { Route as ApiMailInboundRouteImport } from './routes/api/mail.inbound'
import { Route as ApiNidaVerifyRouteImport } from './routes/api/nida.verify'
import { Route as ApiPropertiesManageRouteImport } from './routes/api/properties.manage'
import { Route as ApiPublicCustomerPassRouteImport } from './routes/api/public/customer-pass'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'
import { Route as ApiPublicHomeRouteImport } from './routes/api/public/home'
import { Route as ApiPublicPropertiesRouteImport } from './routes/api/public/properties'
import { Route as ApiPublicPropertyCategoriesRouteImport } from './routes/api/public/property-categories'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard.admin.index'
import { Route as AuthenticatedDashboardAdminContactEditRouteImport } from './routes/_authenticated/dashboard.admin.contact-edit'
import { Route as AuthenticatedDashboardAdminPortfolioRouteImport } from './routes/_authenticated/dashboard.admin.portfolio'
import { Route as AuthenticatedDashboardAdminPortfolioVideosRouteImport } from './routes/_authenticated/dashboard.admin.portfolio-videos'
import { Route as AuthenticatedDashboardAdminReportsRouteImport } from './routes/_authenticated/dashboard.admin.reports'
import { Route as AuthenticatedDashboardAdminVisitTasksRouteImport } from './routes/_authenticated/dashboard.admin.visit-tasks'
import { Route as AuthenticatedDashboardBuyerIndexRouteImport } from './routes/_authenticated/dashboard.buyer.index'
import { Route as AuthenticatedDashboardBuyerBookingsRouteImport } from './routes/_authenticated/dashboard.buyer.bookings'
import { Route as AuthenticatedDashboardBuyerServiceRequestsRouteImport } from './routes/_authenticated/dashboard.buyer.service-requests'
import { Route as AuthenticatedDashboardInquiriesIndexRouteImport } from './routes/_authenticated/dashboard.inquiries.index'
import { Route as AuthenticatedDashboardItIndexRouteImport } from './routes/_authenticated/dashboard.it.index'
import { Route as AuthenticatedDashboardItAuditLogsRouteImport } from './routes/_authenticated/dashboard.it.audit-logs'
import { Route as AuthenticatedDashboardItHomeContentRouteImport } from './routes/_authenticated/dashboard.it.home-content'
import { Route as AuthenticatedDashboardItLuxuryRouteImport } from './routes/_authenticated/dashboard.it.luxury'
import { Route as AuthenticatedDashboardItMediaVerifyRouteImport } from './routes/_authenticated/dashboard.it.media-verify'
import { Route as AuthenticatedDashboardItPasswordResetsRouteImport } from './routes/_authenticated/dashboard.it.password-resets'
import { Route as AuthenticatedDashboardItPropertyOfTheDayRouteImport } from './routes/_authenticated/dashboard.it.property-of-the-day'
import { Route as AuthenticatedDashboardItPropertyTypesRouteImport } from './routes/_authenticated/dashboard.it.property-types'
import { Route as AuthenticatedDashboardItSettingsRouteImport } from './routes/_authenticated/dashboard.it.settings'
import { Route as AuthenticatedDashboardItSubscribersRouteImport } from './routes/_authenticated/dashboard.it.subscribers'
import { Route as AuthenticatedDashboardItSystemHealthRouteImport } from './routes/_authenticated/dashboard.it.system-health'
import { Route as AuthenticatedDashboardItUsersRouteImport } from './routes/_authenticated/dashboard.it.users'
import { Route as AuthenticatedDashboardOwnerBookingsRouteImport } from './routes/_authenticated/dashboard.owner.bookings'
import { Route as AuthenticatedDashboardOwnerReportRouteImport } from './routes/_authenticated/dashboard.owner.report'
import { Route as AuthenticatedDashboardOwnerServiceRequestsRouteImport } from './routes/_authenticated/dashboard.owner.service-requests'
import { Route as AuthenticatedDashboardPropertiesIndexRouteImport } from './routes/_authenticated/dashboard.properties.index'
import { Route as AuthenticatedDashboardPropertiesNewRouteImport } from './routes/_authenticated/dashboard.properties.new'
import { Route as AuthenticatedDashboardReceptionistIndexRouteImport } from './routes/_authenticated/dashboard.receptionist.index'
import { Route as AuthenticatedDashboardReceptionistRegisterRouteImport } from './routes/_authenticated/dashboard.receptionist.register'
import { Route as AuthenticatedDashboardItStaffNewRouteImport } from './routes/_authenticated/dashboard.it.staff.new'
import { Route as AuthenticatedDashboardPropertiesPropertyIdUnitsRouteImport } from './routes/_authenticated/dashboard.properties.$propertyId.units'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteInvestorsRoute = SiteInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => SiteRoute,
} as any)
const SiteListPropertyRoute = SiteListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLuxuryAccessRoute = SiteLuxuryAccessRouteImport.update({
  id: '/luxury-access',
  path: '/luxury-access',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortfolioRoute = SitePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVerifyAccessRoute = SiteVerifyAccessRouteImport.update({
  id: '/verify-access',
  path: '/verify-access',
  getParentRoute: () => SiteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeaturesRoute = ApiFeaturesRouteImport.update({
  id: '/api/features',
  path: '/api/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsCountRoute = ApiNotificationsCountRouteImport.update({
  id: '/api/notifications-count',
  path: '/api/notifications-count',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertyTypesRoute = ApiPropertyTypesRouteImport.update({
  id: '/api/property-types',
  path: '/api/property-types',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardAgentRoute =
  AuthenticatedDashboardAgentRouteImport.update({
    id: '/dashboard/agent',
    path: '/dashboard/agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/dashboard/bookings',
    path: '/dashboard/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/dashboard/messages',
    path: '/dashboard/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/dashboard/notifications',
    path: '/dashboard/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOwnerRoute =
  AuthenticatedDashboardOwnerRouteImport.update({
    id: '/dashboard/owner',
    path: '/dashboard/owner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceptionistRoute =
  AuthenticatedDashboardReceptionistRouteImport.update({
    id: '/dashboard/receptionist',
    path: '/dashboard/receptionist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardServiceCatalogRoute =
  AuthenticatedDashboardServiceCatalogRouteImport.update({
    id: '/dashboard/service-catalog',
    path: '/dashboard/service-catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardServiceRequestsRoute =
  AuthenticatedDashboardServiceRequestsRouteImport.update({
    id: '/dashboard/service-requests',
    path: '/dashboard/service-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SiteCustomerPassTokenRoute = SiteCustomerPassTokenRouteImport.update({
  id: '/customer-pass/$token',
  path: '/customer-pass/$token',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortfolioVideosRoute = SitePortfolioVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => SitePortfolioRoute,
} as any)
const SitePropertiesIndexRoute = SitePropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePropertiesSlugRoute = SitePropertiesSlugRouteImport.update({
  id: '/properties/$slug',
  path: '/properties/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOtpRoute = ApiAuthOtpRouteImport.update({
  id: '/api/auth/otp',
  path: '/api/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCustomerAccessRoute = ApiCustomerAccessRouteImport.update({
  id: '/api/customer/access',
  path: '/api/customer/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailInboundRoute = ApiMailInboundRouteImport.update({
  id: '/api/mail/inbound',
  path: '/api/mail/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNidaVerifyRoute = ApiNidaVerifyRouteImport.update({
  id: '/api/nida/verify',
  path: '/api/nida/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesManageRoute = ApiPropertiesManageRouteImport.update({
  id: '/api/properties/manage',
  path: '/api/properties/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCustomerPassRoute = ApiPublicCustomerPassRouteImport.update({
  id: '/api/public/customer-pass',
  path: '/api/public/customer-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHomeRoute = ApiPublicHomeRouteImport.update({
  id: '/api/public/home',
  path: '/api/public/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesRoute = ApiPublicPropertiesRouteImport.update({
  id: '/api/public/properties',
  path: '/api/public/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertyCategoriesRoute =
  ApiPublicPropertyCategoriesRouteImport.update({
    id: '/api/public/property-categories',
    path: '/api/public/property-categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/dashboard/admin/',
    path: '/dashboard/admin/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminContactEditRoute =
  AuthenticatedDashboardAdminContactEditRouteImport.update({
    id: '/dashboard/admin/contact-edit',
    path: '/dashboard/admin/contact-edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminPortfolioRoute =
  AuthenticatedDashboardAdminPortfolioRouteImport.update({
    id: '/dashboard/admin/portfolio',
    path: '/dashboard/admin/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminPortfolioVideosRoute =
  AuthenticatedDashboardAdminPortfolioVideosRouteImport.update({
    id: '/dashboard/admin/portfolio-videos',
    path: '/dashboard/admin/portfolio-videos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminReportsRoute =
  AuthenticatedDashboardAdminReportsRouteImport.update({
    id: '/dashboard/admin/reports',
    path: '/dashboard/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminVisitTasksRoute =
  AuthenticatedDashboardAdminVisitTasksRouteImport.update({
    id: '/dashboard/admin/visit-tasks',
    path: '/dashboard/admin/visit-tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBuyerIndexRoute =
  AuthenticatedDashboardBuyerIndexRouteImport.update({
    id: '/dashboard/buyer/',
    path: '/dashboard/buyer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBuyerBookingsRoute =
  AuthenticatedDashboardBuyerBookingsRouteImport.update({
    id: '/dashboard/buyer/bookings',
    path: '/dashboard/buyer/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBuyerServiceRequestsRoute =
  AuthenticatedDashboardBuyerServiceRequestsRouteImport.update({
    id: '/dashboard/buyer/service-requests',
    path: '/dashboard/buyer/service-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardInquiriesIndexRoute =
  AuthenticatedDashboardInquiriesIndexRouteImport.update({
    id: '/dashboard/inquiries/',
    path: '/dashboard/inquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItIndexRoute =
  AuthenticatedDashboardItIndexRouteImport.update({
    id: '/dashboard/it/',
    path: '/dashboard/it/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItAuditLogsRoute =
  AuthenticatedDashboardItAuditLogsRouteImport.update({
    id: '/dashboard/it/audit-logs',
    path: '/dashboard/it/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItHomeContentRoute =
  AuthenticatedDashboardItHomeContentRouteImport.update({
    id: '/dashboard/it/home-content',
    path: '/dashboard/it/home-content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItLuxuryRoute =
  AuthenticatedDashboardItLuxuryRouteImport.update({
    id: '/dashboard/it/luxury',
    path: '/dashboard/it/luxury',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItMediaVerifyRoute =
  AuthenticatedDashboardItMediaVerifyRouteImport.update({
    id: '/dashboard/it/media-verify',
    path: '/dashboard/it/media-verify',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItPasswordResetsRoute =
  AuthenticatedDashboardItPasswordResetsRouteImport.update({
    id: '/dashboard/it/password-resets',
    path: '/dashboard/it/password-resets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItPropertyOfTheDayRoute =
  AuthenticatedDashboardItPropertyOfTheDayRouteImport.update({
    id: '/dashboard/it/property-of-the-day',
    path: '/dashboard/it/property-of-the-day',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItPropertyTypesRoute =
  AuthenticatedDashboardItPropertyTypesRouteImport.update({
    id: '/dashboard/it/property-types',
    path: '/dashboard/it/property-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItSettingsRoute =
  AuthenticatedDashboardItSettingsRouteImport.update({
    id: '/dashboard/it/settings',
    path: '/dashboard/it/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItSubscribersRoute =
  AuthenticatedDashboardItSubscribersRouteImport.update({
    id: '/dashboard/it/subscribers',
    path: '/dashboard/it/subscribers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItSystemHealthRoute =
  AuthenticatedDashboardItSystemHealthRouteImport.update({
    id: '/dashboard/it/system-health',
    path: '/dashboard/it/system-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardItUsersRoute =
  AuthenticatedDashboardItUsersRouteImport.update({
    id: '/dashboard/it/users',
    path: '/dashboard/it/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOwnerBookingsRoute =
  AuthenticatedDashboardOwnerBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardOwnerRoute,
  } as any)
const AuthenticatedDashboardOwnerReportRoute =
  AuthenticatedDashboardOwnerReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedDashboardOwnerRoute,
  } as any)
const AuthenticatedDashboardOwnerServiceRequestsRoute =
  AuthenticatedDashboardOwnerServiceRequestsRouteImport.update({
    id: '/service-requests',
    path: '/service-requests',
    getParentRoute: () => AuthenticatedDashboardOwnerRoute,
  } as any)
const AuthenticatedDashboardPropertiesIndexRoute =
  AuthenticatedDashboardPropertiesIndexRouteImport.update({
    id: '/dashboard/properties/',
    path: '/dashboard/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPropertiesNewRoute =
  AuthenticatedDashboardPropertiesNewRouteImport.update({
    id: '/dashboard/properties/new',
    path: '/dashboard/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReceptionistIndexRoute =
  AuthenticatedDashboardReceptionistIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardReceptionistRoute,
  } as any)
const AuthenticatedDashboardReceptionistRegisterRoute =
  AuthenticatedDashboardReceptionistRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedDashboardReceptionistRoute,
  } as any)
const AuthenticatedDashboardItStaffNewRoute =
  AuthenticatedDashboardItStaffNewRouteImport.update({
    id: '/dashboard/it/staff/new',
    path: '/dashboard/it/staff/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPropertiesPropertyIdUnitsRoute =
  AuthenticatedDashboardPropertiesPropertyIdUnitsRouteImport.update({
    id: '/dashboard/properties/$propertyId/units',
    path: '/dashboard/properties/$propertyId/units',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/investors': typeof SiteInvestorsRoute
  '/list-property': typeof SiteListPropertyRoute
  '/luxury-access': typeof SiteLuxuryAccessRoute
  '/portfolio': typeof SitePortfolioRouteWithChildren
  '/services': typeof SiteServicesRoute
  '/verify-access': typeof SiteVerifyAccessRoute
  '/api/chat': typeof ApiChatRoute
  '/api/features': typeof ApiFeaturesRoute
  '/api/notifications-count': typeof ApiNotificationsCountRoute
  '/api/property-types': typeof ApiPropertyTypesRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRouteWithChildren
  '/dashboard/receptionist': typeof AuthenticatedDashboardReceptionistRouteWithChildren
  '/dashboard/service-catalog': typeof AuthenticatedDashboardServiceCatalogRoute
  '/dashboard/service-requests': typeof AuthenticatedDashboardServiceRequestsRoute
  '/customer-pass/$token': typeof SiteCustomerPassTokenRoute
  '/portfolio/videos': typeof SitePortfolioVideosRoute
  '/properties/$slug': typeof SitePropertiesSlugRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/otp': typeof ApiAuthOtpRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/customer/access': typeof ApiCustomerAccessRoute
  '/api/mail/inbound': typeof ApiMailInboundRoute
  '/api/nida/verify': typeof ApiNidaVerifyRoute
  '/api/properties/manage': typeof ApiPropertiesManageRoute
  '/api/public/customer-pass': typeof ApiPublicCustomerPassRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/home': typeof ApiPublicHomeRoute
  '/api/public/properties': typeof ApiPublicPropertiesRoute
  '/api/public/property-categories': typeof ApiPublicPropertyCategoriesRoute
  '/properties/': typeof SitePropertiesIndexRoute
  '/dashboard/admin/contact-edit': typeof AuthenticatedDashboardAdminContactEditRoute
  '/dashboard/admin/portfolio': typeof AuthenticatedDashboardAdminPortfolioRoute
  '/dashboard/admin/portfolio-videos': typeof AuthenticatedDashboardAdminPortfolioVideosRoute
  '/dashboard/admin/reports': typeof AuthenticatedDashboardAdminReportsRoute
  '/dashboard/admin/visit-tasks': typeof AuthenticatedDashboardAdminVisitTasksRoute
  '/dashboard/buyer/bookings': typeof AuthenticatedDashboardBuyerBookingsRoute
  '/dashboard/buyer/service-requests': typeof AuthenticatedDashboardBuyerServiceRequestsRoute
  '/dashboard/it/audit-logs': typeof AuthenticatedDashboardItAuditLogsRoute
  '/dashboard/it/home-content': typeof AuthenticatedDashboardItHomeContentRoute
  '/dashboard/it/luxury': typeof AuthenticatedDashboardItLuxuryRoute
  '/dashboard/it/media-verify': typeof AuthenticatedDashboardItMediaVerifyRoute
  '/dashboard/it/password-resets': typeof AuthenticatedDashboardItPasswordResetsRoute
  '/dashboard/it/property-of-the-day': typeof AuthenticatedDashboardItPropertyOfTheDayRoute
  '/dashboard/it/property-types': typeof AuthenticatedDashboardItPropertyTypesRoute
  '/dashboard/it/settings': typeof AuthenticatedDashboardItSettingsRoute
  '/dashboard/it/subscribers': typeof AuthenticatedDashboardItSubscribersRoute
  '/dashboard/it/system-health': typeof AuthenticatedDashboardItSystemHealthRoute
  '/dashboard/it/users': typeof AuthenticatedDashboardItUsersRoute
  '/dashboard/owner/bookings': typeof AuthenticatedDashboardOwnerBookingsRoute
  '/dashboard/owner/report': typeof AuthenticatedDashboardOwnerReportRoute
  '/dashboard/owner/service-requests': typeof AuthenticatedDashboardOwnerServiceRequestsRoute
  '/dashboard/properties/new': typeof AuthenticatedDashboardPropertiesNewRoute
  '/dashboard/receptionist/register': typeof AuthenticatedDashboardReceptionistRegisterRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/buyer/': typeof AuthenticatedDashboardBuyerIndexRoute
  '/dashboard/inquiries/': typeof AuthenticatedDashboardInquiriesIndexRoute
  '/dashboard/it/': typeof AuthenticatedDashboardItIndexRoute
  '/dashboard/properties/': typeof AuthenticatedDashboardPropertiesIndexRoute
  '/dashboard/receptionist/': typeof AuthenticatedDashboardReceptionistIndexRoute
  '/dashboard/it/staff/new': typeof AuthenticatedDashboardItStaffNewRoute
  '/dashboard/properties/$propertyId/units': typeof AuthenticatedDashboardPropertiesPropertyIdUnitsRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/contact': typeof SiteContactRoute
  '/investors': typeof SiteInvestorsRoute
  '/list-property': typeof SiteListPropertyRoute
  '/luxury-access': typeof SiteLuxuryAccessRoute
  '/portfolio': typeof SitePortfolioRouteWithChildren
  '/services': typeof SiteServicesRoute
  '/verify-access': typeof SiteVerifyAccessRoute
  '/api/chat': typeof ApiChatRoute
  '/api/features': typeof ApiFeaturesRoute
  '/api/notifications-count': typeof ApiNotificationsCountRoute
  '/api/property-types': typeof ApiPropertyTypesRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRouteWithChildren
  '/dashboard/service-catalog': typeof AuthenticatedDashboardServiceCatalogRoute
  '/dashboard/service-requests': typeof AuthenticatedDashboardServiceRequestsRoute
  '/customer-pass/$token': typeof SiteCustomerPassTokenRoute
  '/portfolio/videos': typeof SitePortfolioVideosRoute
  '/properties/$slug': typeof SitePropertiesSlugRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/otp': typeof ApiAuthOtpRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/customer/access': typeof ApiCustomerAccessRoute
  '/api/mail/inbound': typeof ApiMailInboundRoute
  '/api/nida/verify': typeof ApiNidaVerifyRoute
  '/api/properties/manage': typeof ApiPropertiesManageRoute
  '/api/public/customer-pass': typeof ApiPublicCustomerPassRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/home': typeof ApiPublicHomeRoute
  '/api/public/properties': typeof ApiPublicPropertiesRoute
  '/api/public/property-categories': typeof ApiPublicPropertyCategoriesRoute
  '/properties': typeof SitePropertiesIndexRoute
  '/dashboard/admin/contact-edit': typeof AuthenticatedDashboardAdminContactEditRoute
  '/dashboard/admin/portfolio': typeof AuthenticatedDashboardAdminPortfolioRoute
  '/dashboard/admin/portfolio-videos': typeof AuthenticatedDashboardAdminPortfolioVideosRoute
  '/dashboard/admin/reports': typeof AuthenticatedDashboardAdminReportsRoute
  '/dashboard/admin/visit-tasks': typeof AuthenticatedDashboardAdminVisitTasksRoute
  '/dashboard/buyer/bookings': typeof AuthenticatedDashboardBuyerBookingsRoute
  '/dashboard/buyer/service-requests': typeof AuthenticatedDashboardBuyerServiceRequestsRoute
  '/dashboard/it/audit-logs': typeof AuthenticatedDashboardItAuditLogsRoute
  '/dashboard/it/home-content': typeof AuthenticatedDashboardItHomeContentRoute
  '/dashboard/it/luxury': typeof AuthenticatedDashboardItLuxuryRoute
  '/dashboard/it/media-verify': typeof AuthenticatedDashboardItMediaVerifyRoute
  '/dashboard/it/password-resets': typeof AuthenticatedDashboardItPasswordResetsRoute
  '/dashboard/it/property-of-the-day': typeof AuthenticatedDashboardItPropertyOfTheDayRoute
  '/dashboard/it/property-types': typeof AuthenticatedDashboardItPropertyTypesRoute
  '/dashboard/it/settings': typeof AuthenticatedDashboardItSettingsRoute
  '/dashboard/it/subscribers': typeof AuthenticatedDashboardItSubscribersRoute
  '/dashboard/it/system-health': typeof AuthenticatedDashboardItSystemHealthRoute
  '/dashboard/it/users': typeof AuthenticatedDashboardItUsersRoute
  '/dashboard/owner/bookings': typeof AuthenticatedDashboardOwnerBookingsRoute
  '/dashboard/owner/report': typeof AuthenticatedDashboardOwnerReportRoute
  '/dashboard/owner/service-requests': typeof AuthenticatedDashboardOwnerServiceRequestsRoute
  '/dashboard/properties/new': typeof AuthenticatedDashboardPropertiesNewRoute
  '/dashboard/receptionist/register': typeof AuthenticatedDashboardReceptionistRegisterRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
  '/dashboard/buyer': typeof AuthenticatedDashboardBuyerIndexRoute
  '/dashboard/inquiries': typeof AuthenticatedDashboardInquiriesIndexRoute
  '/dashboard/it': typeof AuthenticatedDashboardItIndexRoute
  '/dashboard/properties': typeof AuthenticatedDashboardPropertiesIndexRoute
  '/dashboard/receptionist': typeof AuthenticatedDashboardReceptionistIndexRoute
  '/dashboard/it/staff/new': typeof AuthenticatedDashboardItStaffNewRoute
  '/dashboard/properties/$propertyId/units': typeof AuthenticatedDashboardPropertiesPropertyIdUnitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/blog': typeof SiteBlogRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/investors': typeof SiteInvestorsRoute
  '/_site/list-property': typeof SiteListPropertyRoute
  '/_site/luxury-access': typeof SiteLuxuryAccessRoute
  '/_site/portfolio': typeof SitePortfolioRouteWithChildren
  '/_site/services': typeof SiteServicesRoute
  '/_site/verify-access': typeof SiteVerifyAccessRoute
  '/api/chat': typeof ApiChatRoute
  '/api/features': typeof ApiFeaturesRoute
  '/api/notifications-count': typeof ApiNotificationsCountRoute
  '/api/property-types': typeof ApiPropertyTypesRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/_site/': typeof SiteIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/owner': typeof AuthenticatedDashboardOwnerRouteWithChildren
  '/_authenticated/dashboard/receptionist': typeof AuthenticatedDashboardReceptionistRouteWithChildren
  '/_authenticated/dashboard/service-catalog': typeof AuthenticatedDashboardServiceCatalogRoute
  '/_authenticated/dashboard/service-requests': typeof AuthenticatedDashboardServiceRequestsRoute
  '/_site/customer-pass/$token': typeof SiteCustomerPassTokenRoute
  '/_site/portfolio/videos': typeof SitePortfolioVideosRoute
  '/_site/properties/$slug': typeof SitePropertiesSlugRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/otp': typeof ApiAuthOtpRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/customer/access': typeof ApiCustomerAccessRoute
  '/api/mail/inbound': typeof ApiMailInboundRoute
  '/api/nida/verify': typeof ApiNidaVerifyRoute
  '/api/properties/manage': typeof ApiPropertiesManageRoute
  '/api/public/customer-pass': typeof ApiPublicCustomerPassRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/home': typeof ApiPublicHomeRoute
  '/api/public/properties': typeof ApiPublicPropertiesRoute
  '/api/public/property-categories': typeof ApiPublicPropertyCategoriesRoute
  '/_site/properties/': typeof SitePropertiesIndexRoute
  '/_authenticated/dashboard/admin/contact-edit': typeof AuthenticatedDashboardAdminContactEditRoute
  '/_authenticated/dashboard/admin/portfolio': typeof AuthenticatedDashboardAdminPortfolioRoute
  '/_authenticated/dashboard/admin/portfolio-videos': typeof AuthenticatedDashboardAdminPortfolioVideosRoute
  '/_authenticated/dashboard/admin/reports': typeof AuthenticatedDashboardAdminReportsRoute
  '/_authenticated/dashboard/admin/visit-tasks': typeof AuthenticatedDashboardAdminVisitTasksRoute
  '/_authenticated/dashboard/buyer/bookings': typeof AuthenticatedDashboardBuyerBookingsRoute
  '/_authenticated/dashboard/buyer/service-requests': typeof AuthenticatedDashboardBuyerServiceRequestsRoute
  '/_authenticated/dashboard/it/audit-logs': typeof AuthenticatedDashboardItAuditLogsRoute
  '/_authenticated/dashboard/it/home-content': typeof AuthenticatedDashboardItHomeContentRoute
  '/_authenticated/dashboard/it/luxury': typeof AuthenticatedDashboardItLuxuryRoute
  '/_authenticated/dashboard/it/media-verify': typeof AuthenticatedDashboardItMediaVerifyRoute
  '/_authenticated/dashboard/it/password-resets': typeof AuthenticatedDashboardItPasswordResetsRoute
  '/_authenticated/dashboard/it/property-of-the-day': typeof AuthenticatedDashboardItPropertyOfTheDayRoute
  '/_authenticated/dashboard/it/property-types': typeof AuthenticatedDashboardItPropertyTypesRoute
  '/_authenticated/dashboard/it/settings': typeof AuthenticatedDashboardItSettingsRoute
  '/_authenticated/dashboard/it/subscribers': typeof AuthenticatedDashboardItSubscribersRoute
  '/_authenticated/dashboard/it/system-health': typeof AuthenticatedDashboardItSystemHealthRoute
  '/_authenticated/dashboard/it/users': typeof AuthenticatedDashboardItUsersRoute
  '/_authenticated/dashboard/owner/bookings': typeof AuthenticatedDashboardOwnerBookingsRoute
  '/_authenticated/dashboard/owner/report': typeof AuthenticatedDashboardOwnerReportRoute
  '/_authenticated/dashboard/owner/service-requests': typeof AuthenticatedDashboardOwnerServiceRequestsRoute
  '/_authenticated/dashboard/properties/new': typeof AuthenticatedDashboardPropertiesNewRoute
  '/_authenticated/dashboard/receptionist/register': typeof AuthenticatedDashboardReceptionistRegisterRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
  '/_authenticated/dashboard/buyer/': typeof AuthenticatedDashboardBuyerIndexRoute
  '/_authenticated/dashboard/inquiries/': typeof AuthenticatedDashboardInquiriesIndexRoute
  '/_authenticated/dashboard/it/': typeof AuthenticatedDashboardItIndexRoute
  '/_authenticated/dashboard/properties/': typeof AuthenticatedDashboardPropertiesIndexRoute
  '/_authenticated/dashboard/receptionist/': typeof AuthenticatedDashboardReceptionistIndexRoute
  '/_authenticated/dashboard/it/staff/new': typeof AuthenticatedDashboardItStaffNewRoute
  '/_authenticated/dashboard/properties/$propertyId/units': typeof AuthenticatedDashboardPropertiesPropertyIdUnitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/blog'
    | '/contact'
    | '/investors'
    | '/list-property'
    | '/luxury-access'
    | '/portfolio'
    | '/services'
    | '/verify-access'
    | '/api/chat'
    | '/api/features'
    | '/api/notifications-count'
    | '/api/property-types'
    | '/auth/change-password'
    | '/auth/password-reset'
    | '/auth/verify'
    | '/auth/welcome'
    | '/auth/'
    | '/dashboard/agent'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/owner'
    | '/dashboard/receptionist'
    | '/dashboard/service-catalog'
    | '/dashboard/service-requests'
    | '/customer-pass/$token'
    | '/portfolio/videos'
    | '/properties/$slug'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/otp'
    | '/api/auth/signup'
    | '/api/customer/access'
    | '/api/mail/inbound'
    | '/api/nida/verify'
    | '/api/properties/manage'
    | '/api/public/customer-pass'
    | '/api/public/flutterwave-webhook'
    | '/api/public/home'
    | '/api/public/properties'
    | '/api/public/property-categories'
    | '/properties/'
    | '/dashboard/admin/contact-edit'
    | '/dashboard/admin/portfolio'
    | '/dashboard/admin/portfolio-videos'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/visit-tasks'
    | '/dashboard/buyer/bookings'
    | '/dashboard/buyer/service-requests'
    | '/dashboard/it/audit-logs'
    | '/dashboard/it/home-content'
    | '/dashboard/it/luxury'
    | '/dashboard/it/media-verify'
    | '/dashboard/it/password-resets'
    | '/dashboard/it/property-of-the-day'
    | '/dashboard/it/property-types'
    | '/dashboard/it/settings'
    | '/dashboard/it/subscribers'
    | '/dashboard/it/system-health'
    | '/dashboard/it/users'
    | '/dashboard/owner/bookings'
    | '/dashboard/owner/report'
    | '/dashboard/owner/service-requests'
    | '/dashboard/properties/new'
    | '/dashboard/receptionist/register'
    | '/dashboard/admin/'
    | '/dashboard/buyer/'
    | '/dashboard/inquiries/'
    | '/dashboard/it/'
    | '/dashboard/properties/'
    | '/dashboard/receptionist/'
    | '/dashboard/it/staff/new'
    | '/dashboard/properties/$propertyId/units'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/investors'
    | '/list-property'
    | '/luxury-access'
    | '/portfolio'
    | '/services'
    | '/verify-access'
    | '/api/chat'
    | '/api/features'
    | '/api/notifications-count'
    | '/api/property-types'
    | '/auth/change-password'
    | '/auth/password-reset'
    | '/auth/verify'
    | '/auth/welcome'
    | '/auth'
    | '/dashboard/agent'
    | '/dashboard/bookings'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/owner'
    | '/dashboard/service-catalog'
    | '/dashboard/service-requests'
    | '/customer-pass/$token'
    | '/portfolio/videos'
    | '/properties/$slug'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/otp'
    | '/api/auth/signup'
    | '/api/customer/access'
    | '/api/mail/inbound'
    | '/api/nida/verify'
    | '/api/properties/manage'
    | '/api/public/customer-pass'
    | '/api/public/flutterwave-webhook'
    | '/api/public/home'
    | '/api/public/properties'
    | '/api/public/property-categories'
    | '/properties'
    | '/dashboard/admin/contact-edit'
    | '/dashboard/admin/portfolio'
    | '/dashboard/admin/portfolio-videos'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/visit-tasks'
    | '/dashboard/buyer/bookings'
    | '/dashboard/buyer/service-requests'
    | '/dashboard/it/audit-logs'
    | '/dashboard/it/home-content'
    | '/dashboard/it/luxury'
    | '/dashboard/it/media-verify'
    | '/dashboard/it/password-resets'
    | '/dashboard/it/property-of-the-day'
    | '/dashboard/it/property-types'
    | '/dashboard/it/settings'
    | '/dashboard/it/subscribers'
    | '/dashboard/it/system-health'
    | '/dashboard/it/users'
    | '/dashboard/owner/bookings'
    | '/dashboard/owner/report'
    | '/dashboard/owner/service-requests'
    | '/dashboard/properties/new'
    | '/dashboard/receptionist/register'
    | '/dashboard/admin'
    | '/dashboard/buyer'
    | '/dashboard/inquiries'
    | '/dashboard/it'
    | '/dashboard/properties'
    | '/dashboard/receptionist'
    | '/dashboard/it/staff/new'
    | '/dashboard/properties/$propertyId/units'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/auth'
    | '/_site/about'
    | '/_site/blog'
    | '/_site/contact'
    | '/_site/investors'
    | '/_site/list-property'
    | '/_site/luxury-access'
    | '/_site/portfolio'
    | '/_site/services'
    | '/_site/verify-access'
    | '/api/chat'
    | '/api/features'
    | '/api/notifications-count'
    | '/api/property-types'
    | '/auth/change-password'
    | '/auth/password-reset'
    | '/auth/verify'
    | '/auth/welcome'
    | '/_site/'
    | '/auth/'
    | '/_authenticated/dashboard/agent'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/owner'
    | '/_authenticated/dashboard/receptionist'
    | '/_authenticated/dashboard/service-catalog'
    | '/_authenticated/dashboard/service-requests'
    | '/_site/customer-pass/$token'
    | '/_site/portfolio/videos'
    | '/_site/properties/$slug'
    | '/api/auth/change-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/otp'
    | '/api/auth/signup'
    | '/api/customer/access'
    | '/api/mail/inbound'
    | '/api/nida/verify'
    | '/api/properties/manage'
    | '/api/public/customer-pass'
    | '/api/public/flutterwave-webhook'
    | '/api/public/home'
    | '/api/public/properties'
    | '/api/public/property-categories'
    | '/_site/properties/'
    | '/_authenticated/dashboard/admin/contact-edit'
    | '/_authenticated/dashboard/admin/portfolio'
    | '/_authenticated/dashboard/admin/portfolio-videos'
    | '/_authenticated/dashboard/admin/reports'
    | '/_authenticated/dashboard/admin/visit-tasks'
    | '/_authenticated/dashboard/buyer/bookings'
    | '/_authenticated/dashboard/buyer/service-requests'
    | '/_authenticated/dashboard/it/audit-logs'
    | '/_authenticated/dashboard/it/home-content'
    | '/_authenticated/dashboard/it/luxury'
    | '/_authenticated/dashboard/it/media-verify'
    | '/_authenticated/dashboard/it/password-resets'
    | '/_authenticated/dashboard/it/property-of-the-day'
    | '/_authenticated/dashboard/it/property-types'
    | '/_authenticated/dashboard/it/settings'
    | '/_authenticated/dashboard/it/subscribers'
    | '/_authenticated/dashboard/it/system-health'
    | '/_authenticated/dashboard/it/users'
    | '/_authenticated/dashboard/owner/bookings'
    | '/_authenticated/dashboard/owner/report'
    | '/_authenticated/dashboard/owner/service-requests'
    | '/_authenticated/dashboard/properties/new'
    | '/_authenticated/dashboard/receptionist/register'
    | '/_authenticated/dashboard/admin/'
    | '/_authenticated/dashboard/buyer/'
    | '/_authenticated/dashboard/inquiries/'
    | '/_authenticated/dashboard/it/'
    | '/_authenticated/dashboard/properties/'
    | '/_authenticated/dashboard/receptionist/'
    | '/_authenticated/dashboard/it/staff/new'
    | '/_authenticated/dashboard/properties/$propertyId/units'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiFeaturesRoute: typeof ApiFeaturesRoute
  ApiNotificationsCountRoute: typeof ApiNotificationsCountRoute
  ApiPropertyTypesRoute: typeof ApiPropertyTypesRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthOtpRoute: typeof ApiAuthOtpRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiCustomerAccessRoute: typeof ApiCustomerAccessRoute
  ApiMailInboundRoute: typeof ApiMailInboundRoute
  ApiNidaVerifyRoute: typeof ApiNidaVerifyRoute
  ApiPropertiesManageRoute: typeof ApiPropertiesManageRoute
  ApiPublicCustomerPassRoute: typeof ApiPublicCustomerPassRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
  ApiPublicHomeRoute: typeof ApiPublicHomeRoute
  ApiPublicPropertiesRoute: typeof ApiPublicPropertiesRoute
  ApiPublicPropertyCategoriesRoute: typeof ApiPublicPropertyCategoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/investors': {
      id: '/_site/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof SiteInvestorsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/list-property': {
      id: '/_site/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof SiteListPropertyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/luxury-access': {
      id: '/_site/luxury-access'
      path: '/luxury-access'
      fullPath: '/luxury-access'
      preLoaderRoute: typeof SiteLuxuryAccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portfolio': {
      id: '/_site/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof SitePortfolioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/verify-access': {
      id: '/_site/verify-access'
      path: '/verify-access'
      fullPath: '/verify-access'
      preLoaderRoute: typeof SiteVerifyAccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/features': {
      id: '/api/features'
      path: '/api/features'
      fullPath: '/api/features'
      preLoaderRoute: typeof ApiFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications-count': {
      id: '/api/notifications-count'
      path: '/api/notifications-count'
      fullPath: '/api/notifications-count'
      preLoaderRoute: typeof ApiNotificationsCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/property-types': {
      id: '/api/property-types'
      path: '/api/property-types'
      fullPath: '/api/property-types'
      preLoaderRoute: typeof ApiPropertyTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/agent': {
      id: '/_authenticated/dashboard/agent'
      path: '/dashboard/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof AuthenticatedDashboardAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/owner': {
      id: '/_authenticated/dashboard/owner'
      path: '/dashboard/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receptionist': {
      id: '/_authenticated/dashboard/receptionist'
      path: '/dashboard/receptionist'
      fullPath: '/dashboard/receptionist'
      preLoaderRoute: typeof AuthenticatedDashboardReceptionistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/service-catalog': {
      id: '/_authenticated/dashboard/service-catalog'
      path: '/dashboard/service-catalog'
      fullPath: '/dashboard/service-catalog'
      preLoaderRoute: typeof AuthenticatedDashboardServiceCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/service-requests': {
      id: '/_authenticated/dashboard/service-requests'
      path: '/dashboard/service-requests'
      fullPath: '/dashboard/service-requests'
      preLoaderRoute: typeof AuthenticatedDashboardServiceRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_site/customer-pass/$token': {
      id: '/_site/customer-pass/$token'
      path: '/customer-pass/$token'
      fullPath: '/customer-pass/$token'
      preLoaderRoute: typeof SiteCustomerPassTokenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portfolio/videos': {
      id: '/_site/portfolio/videos'
      path: '/videos'
      fullPath: '/portfolio/videos'
      preLoaderRoute: typeof SitePortfolioVideosRouteImport
      parentRoute: typeof SitePortfolioRoute
    }
    '/_site/properties/': {
      id: '/_site/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof SitePropertiesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/properties/$slug': {
      id: '/_site/properties/$slug'
      path: '/properties/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof SitePropertiesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/otp': {
      id: '/api/auth/otp'
      path: '/api/auth/otp'
      fullPath: '/api/auth/otp'
      preLoaderRoute: typeof ApiAuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/customer/access': {
      id: '/api/customer/access'
      path: '/api/customer/access'
      fullPath: '/api/customer/access'
      preLoaderRoute: typeof ApiCustomerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/inbound': {
      id: '/api/mail/inbound'
      path: '/api/mail/inbound'
      fullPath: '/api/mail/inbound'
      preLoaderRoute: typeof ApiMailInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nida/verify': {
      id: '/api/nida/verify'
      path: '/api/nida/verify'
      fullPath: '/api/nida/verify'
      preLoaderRoute: typeof ApiNidaVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties/manage': {
      id: '/api/properties/manage'
      path: '/api/properties/manage'
      fullPath: '/api/properties/manage'
      preLoaderRoute: typeof ApiPropertiesManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/customer-pass': {
      id: '/api/public/customer-pass'
      path: '/api/public/customer-pass'
      fullPath: '/api/public/customer-pass'
      preLoaderRoute: typeof ApiPublicCustomerPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/home': {
      id: '/api/public/home'
      path: '/api/public/home'
      fullPath: '/api/public/home'
      preLoaderRoute: typeof ApiPublicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties': {
      id: '/api/public/properties'
      path: '/api/public/properties'
      fullPath: '/api/public/properties'
      preLoaderRoute: typeof ApiPublicPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/property-categories': {
      id: '/api/public/property-categories'
      path: '/api/public/property-categories'
      fullPath: '/api/public/property-categories'
      preLoaderRoute: typeof ApiPublicPropertyCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/contact-edit': {
      id: '/_authenticated/dashboard/admin/contact-edit'
      path: '/dashboard/admin/contact-edit'
      fullPath: '/dashboard/admin/contact-edit'
      preLoaderRoute: typeof AuthenticatedDashboardAdminContactEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/portfolio': {
      id: '/_authenticated/dashboard/admin/portfolio'
      path: '/dashboard/admin/portfolio'
      fullPath: '/dashboard/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedDashboardAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/portfolio-videos': {
      id: '/_authenticated/dashboard/admin/portfolio-videos'
      path: '/dashboard/admin/portfolio-videos'
      fullPath: '/dashboard/admin/portfolio-videos'
      preLoaderRoute: typeof AuthenticatedDashboardAdminPortfolioVideosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/reports': {
      id: '/_authenticated/dashboard/admin/reports'
      path: '/dashboard/admin/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof AuthenticatedDashboardAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/visit-tasks': {
      id: '/_authenticated/dashboard/admin/visit-tasks'
      path: '/dashboard/admin/visit-tasks'
      fullPath: '/dashboard/admin/visit-tasks'
      preLoaderRoute: typeof AuthenticatedDashboardAdminVisitTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/buyer/': {
      id: '/_authenticated/dashboard/buyer/'
      path: '/dashboard/buyer'
      fullPath: '/dashboard/buyer/'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/buyer/bookings': {
      id: '/_authenticated/dashboard/buyer/bookings'
      path: '/dashboard/buyer/bookings'
      fullPath: '/dashboard/buyer/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/buyer/service-requests': {
      id: '/_authenticated/dashboard/buyer/service-requests'
      path: '/dashboard/buyer/service-requests'
      fullPath: '/dashboard/buyer/service-requests'
      preLoaderRoute: typeof AuthenticatedDashboardBuyerServiceRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/inquiries/': {
      id: '/_authenticated/dashboard/inquiries/'
      path: '/dashboard/inquiries'
      fullPath: '/dashboard/inquiries/'
      preLoaderRoute: typeof AuthenticatedDashboardInquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/': {
      id: '/_authenticated/dashboard/it/'
      path: '/dashboard/it'
      fullPath: '/dashboard/it/'
      preLoaderRoute: typeof AuthenticatedDashboardItIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/audit-logs': {
      id: '/_authenticated/dashboard/it/audit-logs'
      path: '/dashboard/it/audit-logs'
      fullPath: '/dashboard/it/audit-logs'
      preLoaderRoute: typeof AuthenticatedDashboardItAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/home-content': {
      id: '/_authenticated/dashboard/it/home-content'
      path: '/dashboard/it/home-content'
      fullPath: '/dashboard/it/home-content'
      preLoaderRoute: typeof AuthenticatedDashboardItHomeContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/luxury': {
      id: '/_authenticated/dashboard/it/luxury'
      path: '/dashboard/it/luxury'
      fullPath: '/dashboard/it/luxury'
      preLoaderRoute: typeof AuthenticatedDashboardItLuxuryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/media-verify': {
      id: '/_authenticated/dashboard/it/media-verify'
      path: '/dashboard/it/media-verify'
      fullPath: '/dashboard/it/media-verify'
      preLoaderRoute: typeof AuthenticatedDashboardItMediaVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/password-resets': {
      id: '/_authenticated/dashboard/it/password-resets'
      path: '/dashboard/it/password-resets'
      fullPath: '/dashboard/it/password-resets'
      preLoaderRoute: typeof AuthenticatedDashboardItPasswordResetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/property-of-the-day': {
      id: '/_authenticated/dashboard/it/property-of-the-day'
      path: '/dashboard/it/property-of-the-day'
      fullPath: '/dashboard/it/property-of-the-day'
      preLoaderRoute: typeof AuthenticatedDashboardItPropertyOfTheDayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/property-types': {
      id: '/_authenticated/dashboard/it/property-types'
      path: '/dashboard/it/property-types'
      fullPath: '/dashboard/it/property-types'
      preLoaderRoute: typeof AuthenticatedDashboardItPropertyTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/settings': {
      id: '/_authenticated/dashboard/it/settings'
      path: '/dashboard/it/settings'
      fullPath: '/dashboard/it/settings'
      preLoaderRoute: typeof AuthenticatedDashboardItSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/subscribers': {
      id: '/_authenticated/dashboard/it/subscribers'
      path: '/dashboard/it/subscribers'
      fullPath: '/dashboard/it/subscribers'
      preLoaderRoute: typeof AuthenticatedDashboardItSubscribersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/system-health': {
      id: '/_authenticated/dashboard/it/system-health'
      path: '/dashboard/it/system-health'
      fullPath: '/dashboard/it/system-health'
      preLoaderRoute: typeof AuthenticatedDashboardItSystemHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/it/users': {
      id: '/_authenticated/dashboard/it/users'
      path: '/dashboard/it/users'
      fullPath: '/dashboard/it/users'
      preLoaderRoute: typeof AuthenticatedDashboardItUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/owner/bookings': {
      id: '/_authenticated/dashboard/owner/bookings'
      path: '/bookings'
      fullPath: '/dashboard/owner/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardOwnerRoute
    }
    '/_authenticated/dashboard/owner/report': {
      id: '/_authenticated/dashboard/owner/report'
      path: '/report'
      fullPath: '/dashboard/owner/report'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerReportRouteImport
      parentRoute: typeof AuthenticatedDashboardOwnerRoute
    }
    '/_authenticated/dashboard/owner/service-requests': {
      id: '/_authenticated/dashboard/owner/service-requests'
      path: '/service-requests'
      fullPath: '/dashboard/owner/service-requests'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerServiceRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardOwnerRoute
    }
    '/_authenticated/dashboard/properties/': {
      id: '/_authenticated/dashboard/properties/'
      path: '/dashboard/properties'
      fullPath: '/dashboard/properties/'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/properties/new': {
      id: '/_authenticated/dashboard/properties/new'
      path: '/dashboard/properties/new'
      fullPath: '/dashboard/properties/new'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/receptionist/': {
      id: '/_authenticated/dashboard/receptionist/'
      path: '/'
      fullPath: '/dashboard/receptionist/'
      preLoaderRoute: typeof AuthenticatedDashboardReceptionistIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardReceptionistRoute
    }
    '/_authenticated/dashboard/receptionist/register': {
      id: '/_authenticated/dashboard/receptionist/register'
      path: '/register'
      fullPath: '/dashboard/receptionist/register'
      preLoaderRoute: typeof AuthenticatedDashboardReceptionistRegisterRouteImport
      parentRoute: typeof AuthenticatedDashboardReceptionistRoute
    }
    '/_authenticated/dashboard/it/staff/new': {
      id: '/_authenticated/dashboard/it/staff/new'
      path: '/dashboard/it/staff/new'
      fullPath: '/dashboard/it/staff/new'
      preLoaderRoute: typeof AuthenticatedDashboardItStaffNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/properties/$propertyId/units': {
      id: '/_authenticated/dashboard/properties/$propertyId/units'
      path: '/dashboard/properties/$propertyId/units'
      fullPath: '/dashboard/properties/$propertyId/units'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesPropertyIdUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedDashboardOwnerRouteChildren {
  AuthenticatedDashboardOwnerBookingsRoute: typeof AuthenticatedDashboardOwnerBookingsRoute
  AuthenticatedDashboardOwnerReportRoute: typeof AuthenticatedDashboardOwnerReportRoute
  AuthenticatedDashboardOwnerServiceRequestsRoute: typeof AuthenticatedDashboardOwnerServiceRequestsRoute
}

const AuthenticatedDashboardOwnerRouteChildren: AuthenticatedDashboardOwnerRouteChildren =
  {
    AuthenticatedDashboardOwnerBookingsRoute:
      AuthenticatedDashboardOwnerBookingsRoute,
    AuthenticatedDashboardOwnerReportRoute:
      AuthenticatedDashboardOwnerReportRoute,
    AuthenticatedDashboardOwnerServiceRequestsRoute:
      AuthenticatedDashboardOwnerServiceRequestsRoute,
  }

const AuthenticatedDashboardOwnerRouteWithChildren =
  AuthenticatedDashboardOwnerRoute._addFileChildren(
    AuthenticatedDashboardOwnerRouteChildren,
  )

interface AuthenticatedDashboardReceptionistRouteChildren {
  AuthenticatedDashboardReceptionistRegisterRoute: typeof AuthenticatedDashboardReceptionistRegisterRoute
  AuthenticatedDashboardReceptionistIndexRoute: typeof AuthenticatedDashboardReceptionistIndexRoute
}

const AuthenticatedDashboardReceptionistRouteChildren: AuthenticatedDashboardReceptionistRouteChildren =
  {
    AuthenticatedDashboardReceptionistRegisterRoute:
      AuthenticatedDashboardReceptionistRegisterRoute,
    AuthenticatedDashboardReceptionistIndexRoute:
      AuthenticatedDashboardReceptionistIndexRoute,
  }

const AuthenticatedDashboardReceptionistRouteWithChildren =
  AuthenticatedDashboardReceptionistRoute._addFileChildren(
    AuthenticatedDashboardReceptionistRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardAgentRoute: typeof AuthenticatedDashboardAgentRoute
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardOwnerRoute: typeof AuthenticatedDashboardOwnerRouteWithChildren
  AuthenticatedDashboardReceptionistRoute: typeof AuthenticatedDashboardReceptionistRouteWithChildren
  AuthenticatedDashboardServiceCatalogRoute: typeof AuthenticatedDashboardServiceCatalogRoute
  AuthenticatedDashboardServiceRequestsRoute: typeof AuthenticatedDashboardServiceRequestsRoute
  AuthenticatedDashboardAdminContactEditRoute: typeof AuthenticatedDashboardAdminContactEditRoute
  AuthenticatedDashboardAdminPortfolioRoute: typeof AuthenticatedDashboardAdminPortfolioRoute
  AuthenticatedDashboardAdminPortfolioVideosRoute: typeof AuthenticatedDashboardAdminPortfolioVideosRoute
  AuthenticatedDashboardAdminReportsRoute: typeof AuthenticatedDashboardAdminReportsRoute
  AuthenticatedDashboardAdminVisitTasksRoute: typeof AuthenticatedDashboardAdminVisitTasksRoute
  AuthenticatedDashboardBuyerBookingsRoute: typeof AuthenticatedDashboardBuyerBookingsRoute
  AuthenticatedDashboardBuyerServiceRequestsRoute: typeof AuthenticatedDashboardBuyerServiceRequestsRoute
  AuthenticatedDashboardItAuditLogsRoute: typeof AuthenticatedDashboardItAuditLogsRoute
  AuthenticatedDashboardItHomeContentRoute: typeof AuthenticatedDashboardItHomeContentRoute
  AuthenticatedDashboardItLuxuryRoute: typeof AuthenticatedDashboardItLuxuryRoute
  AuthenticatedDashboardItMediaVerifyRoute: typeof AuthenticatedDashboardItMediaVerifyRoute
  AuthenticatedDashboardItPasswordResetsRoute: typeof AuthenticatedDashboardItPasswordResetsRoute
  AuthenticatedDashboardItPropertyOfTheDayRoute: typeof AuthenticatedDashboardItPropertyOfTheDayRoute
  AuthenticatedDashboardItPropertyTypesRoute: typeof AuthenticatedDashboardItPropertyTypesRoute
  AuthenticatedDashboardItSettingsRoute: typeof AuthenticatedDashboardItSettingsRoute
  AuthenticatedDashboardItSubscribersRoute: typeof AuthenticatedDashboardItSubscribersRoute
  AuthenticatedDashboardItSystemHealthRoute: typeof AuthenticatedDashboardItSystemHealthRoute
  AuthenticatedDashboardItUsersRoute: typeof AuthenticatedDashboardItUsersRoute
  AuthenticatedDashboardPropertiesNewRoute: typeof AuthenticatedDashboardPropertiesNewRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
  AuthenticatedDashboardBuyerIndexRoute: typeof AuthenticatedDashboardBuyerIndexRoute
  AuthenticatedDashboardInquiriesIndexRoute: typeof AuthenticatedDashboardInquiriesIndexRoute
  AuthenticatedDashboardItIndexRoute: typeof AuthenticatedDashboardItIndexRoute
  AuthenticatedDashboardPropertiesIndexRoute: typeof AuthenticatedDashboardPropertiesIndexRoute
  AuthenticatedDashboardItStaffNewRoute: typeof AuthenticatedDashboardItStaffNewRoute
  AuthenticatedDashboardPropertiesPropertyIdUnitsRoute: typeof AuthenticatedDashboardPropertiesPropertyIdUnitsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardAgentRoute: AuthenticatedDashboardAgentRoute,
  AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
  AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
  AuthenticatedDashboardNotificationsRoute:
    AuthenticatedDashboardNotificationsRoute,
  AuthenticatedDashboardOwnerRoute:
    AuthenticatedDashboardOwnerRouteWithChildren,
  AuthenticatedDashboardReceptionistRoute:
    AuthenticatedDashboardReceptionistRouteWithChildren,
  AuthenticatedDashboardServiceCatalogRoute:
    AuthenticatedDashboardServiceCatalogRoute,
  AuthenticatedDashboardServiceRequestsRoute:
    AuthenticatedDashboardServiceRequestsRoute,
  AuthenticatedDashboardAdminContactEditRoute:
    AuthenticatedDashboardAdminContactEditRoute,
  AuthenticatedDashboardAdminPortfolioRoute:
    AuthenticatedDashboardAdminPortfolioRoute,
  AuthenticatedDashboardAdminPortfolioVideosRoute:
    AuthenticatedDashboardAdminPortfolioVideosRoute,
  AuthenticatedDashboardAdminReportsRoute:
    AuthenticatedDashboardAdminReportsRoute,
  AuthenticatedDashboardAdminVisitTasksRoute:
    AuthenticatedDashboardAdminVisitTasksRoute,
  AuthenticatedDashboardBuyerBookingsRoute:
    AuthenticatedDashboardBuyerBookingsRoute,
  AuthenticatedDashboardBuyerServiceRequestsRoute:
    AuthenticatedDashboardBuyerServiceRequestsRoute,
  AuthenticatedDashboardItAuditLogsRoute:
    AuthenticatedDashboardItAuditLogsRoute,
  AuthenticatedDashboardItHomeContentRoute:
    AuthenticatedDashboardItHomeContentRoute,
  AuthenticatedDashboardItLuxuryRoute: AuthenticatedDashboardItLuxuryRoute,
  AuthenticatedDashboardItMediaVerifyRoute:
    AuthenticatedDashboardItMediaVerifyRoute,
  AuthenticatedDashboardItPasswordResetsRoute:
    AuthenticatedDashboardItPasswordResetsRoute,
  AuthenticatedDashboardItPropertyOfTheDayRoute:
    AuthenticatedDashboardItPropertyOfTheDayRoute,
  AuthenticatedDashboardItPropertyTypesRoute:
    AuthenticatedDashboardItPropertyTypesRoute,
  AuthenticatedDashboardItSettingsRoute: AuthenticatedDashboardItSettingsRoute,
  AuthenticatedDashboardItSubscribersRoute:
    AuthenticatedDashboardItSubscribersRoute,
  AuthenticatedDashboardItSystemHealthRoute:
    AuthenticatedDashboardItSystemHealthRoute,
  AuthenticatedDashboardItUsersRoute: AuthenticatedDashboardItUsersRoute,
  AuthenticatedDashboardPropertiesNewRoute:
    AuthenticatedDashboardPropertiesNewRoute,
  AuthenticatedDashboardAdminIndexRoute: AuthenticatedDashboardAdminIndexRoute,
  AuthenticatedDashboardBuyerIndexRoute: AuthenticatedDashboardBuyerIndexRoute,
  AuthenticatedDashboardInquiriesIndexRoute:
    AuthenticatedDashboardInquiriesIndexRoute,
  AuthenticatedDashboardItIndexRoute: AuthenticatedDashboardItIndexRoute,
  AuthenticatedDashboardPropertiesIndexRoute:
    AuthenticatedDashboardPropertiesIndexRoute,
  AuthenticatedDashboardItStaffNewRoute: AuthenticatedDashboardItStaffNewRoute,
  AuthenticatedDashboardPropertiesPropertyIdUnitsRoute:
    AuthenticatedDashboardPropertiesPropertyIdUnitsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SitePortfolioRouteChildren {
  SitePortfolioVideosRoute: typeof SitePortfolioVideosRoute
}

const SitePortfolioRouteChildren: SitePortfolioRouteChildren = {
  SitePortfolioVideosRoute: SitePortfolioVideosRoute,
}

const SitePortfolioRouteWithChildren = SitePortfolioRoute._addFileChildren(
  SitePortfolioRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBlogRoute: typeof SiteBlogRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteInvestorsRoute: typeof SiteInvestorsRoute
  SiteListPropertyRoute: typeof SiteListPropertyRoute
  SiteLuxuryAccessRoute: typeof SiteLuxuryAccessRoute
  SitePortfolioRoute: typeof SitePortfolioRouteWithChildren
  SiteServicesRoute: typeof SiteServicesRoute
  SiteVerifyAccessRoute: typeof SiteVerifyAccessRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCustomerPassTokenRoute: typeof SiteCustomerPassTokenRoute
  SitePropertiesSlugRoute: typeof SitePropertiesSlugRoute
  SitePropertiesIndexRoute: typeof SitePropertiesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBlogRoute: SiteBlogRoute,
  SiteContactRoute: SiteContactRoute,
  SiteInvestorsRoute: SiteInvestorsRoute,
  SiteListPropertyRoute: SiteListPropertyRoute,
  SiteLuxuryAccessRoute: SiteLuxuryAccessRoute,
  SitePortfolioRoute: SitePortfolioRouteWithChildren,
  SiteServicesRoute: SiteServicesRoute,
  SiteVerifyAccessRoute: SiteVerifyAccessRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCustomerPassTokenRoute: SiteCustomerPassTokenRoute,
  SitePropertiesSlugRoute: SitePropertiesSlugRoute,
  SitePropertiesIndexRoute: SitePropertiesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AuthRouteChildren {
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiFeaturesRoute: ApiFeaturesRoute,
  ApiNotificationsCountRoute: ApiNotificationsCountRoute,
  ApiPropertyTypesRoute: ApiPropertyTypesRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthOtpRoute: ApiAuthOtpRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiCustomerAccessRoute: ApiCustomerAccessRoute,
  ApiMailInboundRoute: ApiMailInboundRoute,
  ApiNidaVerifyRoute: ApiNidaVerifyRoute,
  ApiPropertiesManageRoute: ApiPropertiesManageRoute,
  ApiPublicCustomerPassRoute: ApiPublicCustomerPassRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
  ApiPublicHomeRoute: ApiPublicHomeRoute,
  ApiPublicPropertiesRoute: ApiPublicPropertiesRoute,
  ApiPublicPropertyCategoriesRoute: ApiPublicPropertyCategoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
